prompt --application/shared_components/email/templates/token_template
begin
--   Manifest
--     EMAIL TEMPLATE: TOKEN TEMPLATE
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>3780766536418114
,p_default_application_id=>2000004
,p_default_id_offset=>0
,p_default_owner=>'XXSBS'
);
wwv_flow_imp_shared.create_email_template(
 p_id=>wwv_flow_imp.id(57401358389575959)
,p_name=>'TOKEN TEMPLATE'
,p_static_id=>'TOKEN_TEMPLATE'
,p_version_number=>1
,p_subject=>'Softsuite Login Token'
,p_html_body=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<body style="background-color: #f8f8f9; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;">',
'<table border="0" cellpadding="0" cellspacing="0" class="nl-container" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #f8f8f9;" width="100%">',
'<tbody>',
'<tr>',
'<td>',
'<table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-1" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #1aa19c;" width="100%">',
'<tbody>',
'<tr>',
'<td>',
'<table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; background-color: #1aa19c; width: 640px;" width="640">',
'<tbody>',
'<tr>',
'<td class="column column-1" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;'
||'" width="100%">',
'<table border="0" cellpadding="0" cellspacing="0" class="divider_block block-1" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">',
'<tr>',
'<td class="pad">',
'<div align="center" class="alignment">',
'<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">',
'<tr>',
unistr('<td class="divider_inner" style="font-size: 1px; line-height: 1px; border-top: 4px solid #1AA19C;"><span>\200A</span></td>'),
'</tr>',
'</table>',
'</div>',
'</td>',
'</tr>',
'</table>',
'</td>',
'</tr>',
'</tbody>',
'</table>',
'</td>',
'</tr>',
'</tbody>',
'</table>',
'<table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-3" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">',
'<tbody>',
'<tr>',
'<td>',
'<table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #fff; color: #000000; width: 640px;" width="640">',
'<tbody>',
'<tr>',
'<td class="column column-1" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;'
||'" width="100%">',
'<table border="0" cellpadding="0" cellspacing="0" class="divider_block block-2" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">',
'<tr>',
'<td class="pad" style="padding-top:50px;">',
'<div align="center" class="alignment">',
'<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">',
'<tr>',
unistr('<td class="divider_inner" style="font-size: 1px; line-height: 1px; border-top: 0px solid #BBBBBB;"><span>\200A</span></td>'),
'</tr>',
'</table>',
'</div>',
'</td>',
'</tr>',
'</table>',
'<table border="0" cellpadding="0" cellspacing="0" class="text_block block-3" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;" width="100%">',
'<tr>',
'<td class="pad" style="padding-bottom:10px;padding-left:40px;padding-right:40px;padding-top:10px;">',
'<div style="font-family: sans-serif">',
'<div class="" style="font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;">',
'<p style="margin: 0; font-size: 16px; text-align: center; mso-line-height-alt: 19.2px;"><span style="font-size:17px;"><strong>OTP Verification</strong></span></p>',
'</div>',
'</div>',
'</td>',
'</tr>',
'</table>',
'<table border="0" cellpadding="0" cellspacing="0" class="text_block block-4" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;" width="100%">',
'<tr>',
'<td class="pad" style="padding-bottom:10px;padding-left:40px;padding-right:40px;padding-top:10px;">',
'<div style="font-family: sans-serif">',
'<div class="" style="font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;">',
'<p style="margin: 0; font-size: 16px; text-align: center; mso-line-height-alt: 19.2px;"><span style="font-size:15px;">Your token generated is below - this expires in #TIME# minute(s).</span><br/><span style="font-size:13px;"><em>Please note, do not s'
||unistr('hare code with anyone.</em></span>\00A0</p>'),
'</div>',
'</div>',
'</td>',
'</tr>',
'</table>',
'<table border="0" cellpadding="0" cellspacing="0" class="button_block block-5" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">',
'<tr>',
'<td class="pad" style="padding-left:10px;padding-right:10px;padding-top:15px;text-align:center;">',
'<div align="center" class="alignment">',
'',
'<div style="text-decoration:none;display:inline-block;color:#ffffff;background-color:#1d8668;border-radius:60px;width:auto;border-top:0px solid transparent;font-weight:400;border-right:0px solid transparent;border-bottom:0px solid transparent;border-'
||'left:0px solid transparent;padding-top:15px;padding-bottom:15px;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:16px;text-align:center;mso-border-alt:none;word-break:keep-all;"><span'
||' style="padding-left:30px;padding-right:30px;font-size:16px;display:inline-block;letter-spacing:normal;"><span dir="ltr" style="margin: 0; word-break: break-word; line-height: 32px;"><strong>#TOKEN#</strong></span></span></div>',
'</div>',
'</td>',
'</tr>',
'</table>',
'<table border="0" cellpadding="0" cellspacing="0" class="text_block block-6" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;" width="100%">',
'<tr>',
'<td class="pad" style="padding-bottom:10px;padding-left:40px;padding-right:40px;padding-top:10px;">',
'<div style="font-family: sans-serif">',
'<div class="" style="font-size: 12px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 18px; color: #555555; line-height: 1.5;">',
'<p style="margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 21px;">This code is required to finish signing in to <a href="https://app.softsuite.com" rel="noopener" style="text-decoration: underline;" target="_blank"><strong>SoftSUI'
||'TE</strong></a></p>',
unistr('<p style="margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 18px;">\00A0</p>'),
unistr('<p style="margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 18px;">\00A0</p>'),
'<p style="margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 21px;"><strong>Do not recognize this activity? You should consider changing your password.</strong></p>',
'</div>',
'</div>',
'</td>',
'</tr>',
'</table>',
'<table border="0" cellpadding="0" cellspacing="0" class="divider_block block-7" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">',
'<tr>',
'<td class="pad" style="padding-bottom:12px;padding-top:60px;">',
'<div align="center" class="alignment">',
'<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">',
'<tr>',
unistr('<td class="divider_inner" style="font-size: 1px; line-height: 1px; border-top: 0px solid #BBBBBB;"><span>\200A</span></td>'),
'</tr>',
'</table>',
'</div>',
'</td>',
'</tr>',
'</table>',
'</td>',
'</tr>',
'</tbody>',
'</table>',
'</td>',
'</tr>',
'</tbody>',
'</table>',
'<table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-4" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">',
'<tbody>',
'<tr>',
'<td>',
'<table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; background-color: #2b303a; width: 640px;" width="640">',
'<tbody>',
'<tr>',
'<td class="column column-1" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;'
||'" width="100%">',
'<table border="0" cellpadding="0" cellspacing="0" class="divider_block block-1" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">',
'<tr>',
'<td class="pad">',
'<div align="center" class="alignment">',
'<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">',
'<tr>',
unistr('<td class="divider_inner" style="font-size: 1px; line-height: 1px; border-top: 4px solid #1AA19C;"><span>\200A</span></td>'),
'</tr>',
'</table>',
'</div>',
'</td>',
'</tr>',
'</table>',
'<table border="0" cellpadding="0" cellspacing="0" class="text_block block-3" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;" width="100%">',
'<tr>',
'<td class="pad" style="padding-bottom:30px;padding-left:40px;padding-right:40px;padding-top:20px;">',
'<div style="font-family: sans-serif">',
'<div class="" style="font-size: 12px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 14.399999999999999px; color: #ffffff; line-height: 1.2;">',
unistr('<p style="margin: 0; mso-line-height-alt: 14.399999999999999px;">SoftSuite Copyright \00A9 2022</p>'),
'</div>',
'</div>',
'</td>',
'</tr>',
'</table>',
'</td>',
'</tr>',
'</tbody>',
'</table>',
'</td>',
'</tr>',
'</tbody>',
'</table>',
'</td>',
'</tr>',
'</tbody>',
'</table><!-- End -->',
'</body>'))
,p_html_template=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<!DOCTYPE html>',
'<html lang="en" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:v="urn:schemas-microsoft-com:vml">',
'<head>',
'<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>',
'<meta content="width=device-width, initial-scale=1.0" name="viewport"/>',
'<style>',
'* {box-sizing: border-box;}',
'body {margin: 0;padding: 0;}',
'a[x-apple-data-detectors] {color: inherit !important;text-decoration: nherit !important;}',
'#MessageViewBody a {color: inherit;text-decoration: none;}',
'p {line-height: inherit}',
'.desktop_hide,.desktop_hide table {mso-hide: all;display: none;max-height: 0px;overflow: hidden;}',
'@media (max-width:660px) {.desktop_hide table.icons-inner {display: inline-block !important;}',
'.icons-inner {text-align: center;}',
'.icons-inner td {margin: 0 auto;}',
'.image_block img.big,.row-content {width: 100% !important;}',
'.mobile_hide {display: none;}',
'.stack .column {width: 100%;display: block;}',
'.mobile_hide {min-height: 0;max-height: 0;max-width: 0;overflow: hidden;font-size: 0px;}',
'.desktop_hide,.desktop_hide table {display: table !important;max-height: none !important;}}',
'</style>',
'</head>',
'#BODY#',
'</html>'))
,p_text_template=>wwv_flow_string.join(wwv_flow_t_varchar2(
'Your login token is #TOKEN#. ',
'Kindly note that your token expires in #TOKEN# minutes. ',
'Contact support for any assistance.'))
,p_version_scn=>1
);
wwv_flow_imp.component_end;
end;
/
