prompt --application/pages/page_00077
begin
--   Manifest
--     PAGE: 00077
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>3780766536418114
,p_default_application_id=>2000004
,p_default_id_offset=>0
,p_default_owner=>'XXSBS'
);
wwv_flow_imp_page.create_page(
 p_id=>77
,p_name=>'Repayment Details'
,p_alias=>'XG1'
,p_step_title=>'Marketplace Product Details'
,p_autocomplete_on_off=>'OFF'
,p_javascript_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/** Products JS */',
'/**',
' * Dynamic Product Table with Pagination',
' * -------------------------------------',
' */',
'let repaymentData = [];',
'let currentPage = 1;',
'// Data Fetchers',
'const getData = (offset, process, type) => {',
'  apex.server.process(process, {',
'    x01: $v(''P77_COMPANY_ID''),',
'    x02: offset',
'  }, {',
'    dataType: "json",',
'    success: function(data) {',
'        if(type === ''repayment''){',
'            repaymentData = [...data];  ',
'            renderPaymentTablePage(offset);',
'        }',
'        const select = document.getElementById(`${type}-select`);',
'            if (select) {',
'                select.value = offset;',
'        }',
'    },',
'    error: function(jqXHR, textStatus, errorThrown) {',
'      console.error("Error loading product data:", textStatus, errorThrown);',
'    }',
'  });',
'  return false;',
'};',
'',
'// Pagination Handler',
'function apprPaginate(direction, process, item, type, totalCount) {',
'  let current = parseInt($v(item)) || 0;',
'  //const pageSize = 1;',
'  let newOffset = current + (direction);',
'  if (newOffset < 1) newOffset = 1;',
'  if (newOffset > totalCount) newOffset = totalCount;',
'  $s(item, newOffset);',
'  getData(newOffset, process, type);',
'  //changeSelect(newOffset)',
'  return false;',
'}',
'',
'function handlePageChange(selectElement, process, item, type) {',
'  const selectedValue = parseInt(selectElement.value);',
'  console.log("Selected page:", selectedValue);',
'  $s(item, selectedValue);',
'  getData(selectedValue, process, type);',
'  return false;',
'}',
'',
'// Table Rendering Functions',
'const repaymentTableBody = document.getElementById("rep-table-body");',
'',
'function renderPaymentTablePage(page) {',
'  repaymentTableBody.innerHTML = "";',
'  ',
'    const rowsPerPage = 5;',
'    const start = (page - 1) * rowsPerPage;',
'    const end = start + rowsPerPage;',
'    const pageData = repaymentData.slice(start, end);',
'',
'  pageData.forEach(item => {',
'    const row = document.createElement("tr");',
'    row.innerHTML = `',
'      <td>${item.period}</td>',
'      <td>${item.repayment_date}</td>',
unistr('      <td>\20A6${item.repayment_amount}</td>'),
'      <td><span class="status ${item.status}">${item.status}</span></td>',
'      ',
'    `;',
'    repaymentTableBody.appendChild(row);',
'  });',
'}',
'',
'',
'//Modal Redirect Helpers',
'//const modal = document.getElementById(''main-modal'');',
'',
'function afterLoad() {',
'  apex.message.showPageSuccess(''success'');',
'}',
'',
'var modal = document.getElementById(''main-modal'');',
'',
'',
'function afterLoad(){',
'    apex.message.showPageSuccess(''success'');',
'}',
'',
'const redirectToModalPageUpdateProduct = (pageID,productId,loanId) => {',
'    console.log(loanId);',
'        var url = `f?p=#APP_ID#:${pageID}:#SESSION#::NO:RP,${pageID}:P10_PRODUCT_ID,P10_LOAN_ID,P10_HEADER:${productId},${loanId},Approve Loan`; //''f?p='' || l_app || '':''||apex_application.g_x01||'':''||l_session||''::NO::''||l_item_name||'':''||apex_applic'
||'ation.g_x02,',
'        //var url = "f?p=#APP_ID#:"+''201''+":#SESSION#::NO:RP,201:";',
'        url = url.replace("#APP_ID#",&APP_ID.);',
'',
'        url = url.replace("#SESSION#", &SESSION.);',
'        ',
'        apex.server.process("PREPARE_URL", {',
'',
'                    x01: url',
'',
'        }, {',
'',
'        success: function(pData) {',
'',
'        if (pData.success === true) {',
'',
'                apex.navigation.redirect(pData.url);',
'',
'        } else {',
'',
'                console.log("FALSE");',
'',
'        }',
'',
'        },',
'',
'        error: function(request, status, error) {',
'',
unistr('               console.log("status\2014" + status + " error\2014-" + error);'),
'',
'        }',
'',
'    });',
'    ',
'    ',
'            return false;',
'        ',
'};',
'',
'const redirectToMainPageFunc = (pageID) => {',
'        var url = `f?p=#APP_ID#:${pageID}:#SESSION#::NO:RP,${pageID}:`;',
'        url = url.replace("#APP_ID#",&APP_ID.);',
'',
'        url = url.replace("#SESSION#", &SESSION.);',
'',
'        apex.server.process("PREPARE_URL", {',
'',
'                    x01: url',
'',
'        }, {',
'',
'        success: function(pData) {',
'',
'        if (pData.success === true) {',
'',
'                apex.navigation.redirect(pData.url);',
'',
'        } else {',
'',
'                console.log("FALSE");',
'',
'        }',
'',
'        },',
'',
'        error: function(request, status, error) {',
'',
unistr('               console.log("status\2014" + status + " error\2014-" + error);'),
'',
'        }',
'',
'    });',
'    ',
'    ',
'            return false;',
'        ',
'};',
'',
'function open_dialog(){',
' $(''#confirm-action'').dialog(''open''); //calling region id here to open',
'    return false;',
'}',
'',
'function openDeactivateDialog(){',
' $(''#deactivate-action'').dialog(''open''); //calling region id here to open',
'    return false;',
'}',
'',
'function closeMainModal(){',
'    $(''#modalwindow'').modal(''hide'');',
'    //  javascript:apex.navigation.dialog.close(true);',
'    return false;',
'}',
'',
'function closeModal(){',
'    apex.navigation.dialog.close(true);',
'    return false;',
'}',
'function closeInlineModal(){',
'     $(''#confirm-action'').dialog(''close''); ',
'     $(''#deactivate-action'').dialog(''close''); ',
'    return false;',
'}',
'',
'',
'//Filter Functions',
'function filterRepayments() {',
'  const input = document.getElementById(''repayments-search'');',
'  const filter = input.value.toLowerCase();',
'  document.querySelectorAll(''#rep-table-body tr'').forEach(row => {',
'    row.style.display = row.textContent.toLowerCase().includes(filter) ? '''' : ''none'';',
'  });',
'}',
'',
'function confirmCancelLoan(){',
'    apex.message.confirm( "Are you sure you want to cancel this loan?", function( okPressed ) {',
'            if (okPressed) {',
'                apex.server.process("PROCESS_DATA", {}, {',
'                    dataType: "json", // or remove this if returning JSON',
'                        success: function(data) {',
'                            if (data.status === "success") {',
'                                //closeModal();',
'                                ',
'                                window.location.reload();',
'                                //document.getElementById(cancel)',
'                                setTimeout(function() {',
'                                  apex.message.showPageSuccess(''Loan Successfully Canceled'');',
'                                }, 5000);                               ',
'                            } else {',
'                                apex.message.alert(''Failed to cancel loan'');',
'                            }',
'                        },',
'                        error: function(jqXHR, textStatus, errorThrown) {',
'                            console.error("Error:", textStatus, errorThrown);',
'                    }',
'                });',
'            }',
'    }, {',
'        title: "Cancel Loan",',
'        style: "danger",',
'        dialogClasses: "my-custom-class",',
'        iconClasses: "fa fa-question fa-2x",',
'        cancelLabel: "Cancel",',
'        confirmLabel: "I confirm"',
'    } );',
'    return false;',
'}',
'',
'window.onload = () => {',
'  getData(1, ''GET_REPAYMENT_DATA'', ''repayment'');',
'',
'  renderPaymentTablePage(currentPage);',
'};',
''))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/*Back Button*/',
'.icon-button {',
'  display: flex;',
'  align-items: center; /* Vertically center the icon and text */',
'  /* padding: 20px 0px; */',
'  background: #FFFFFF;',
'  color: #000000;',
'  border: none;',
'  border-radius: 5px;',
'  cursor: pointer;',
'  font-size: 16px;',
'  transition: background-color 0.3s;',
'  margin: 8px 0;',
'}',
'',
'.t-HeroRegion-wrap{',
'    padding: 0!important;',
'}',
'.icon {',
'  width: 20px; /* Set the width of the icon */',
'  height: 20px; /* Set the height of the icon */',
'  margin-right: 10px; /* Space between icon and text */',
'}',
'',
'',
'.button-text {',
'  white-space: nowrap; /* Prevent the text from breaking onto a new line */',
'    font-family: Helvetica;',
'    font-size: 16px;',
'    font-weight: 700;',
'    line-height: 18.4px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'}',
'',
'.top-region-header{',
'    display: flex;',
'    align-items: center;',
'    text-align: center;',
'    gap: 8px;',
'}',
'',
'.search-input {',
'    padding: 8px 12px;',
'    border: 1px solid #ccc;',
'    border-radius: 4px;',
'    font-family: Helvetica;',
'    font-size: 14px;',
'    width: 200px;',
'}',
'',
'.top-region-header p {',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-style: Bold;',
'font-size: 16px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #000000;',
'}',
'',
'.top-region-header p::before {',
'  content: "|";',
'   margin-right:8px; ',
'  color: #DDDDDD;',
'}',
'',
'.loan-header{',
'display: flex;',
'border: 1px solid #D4D8E2;',
'border-radius: 12px;',
'margin-top: 20px;',
'overflow: hidden;',
'}',
'.summary-item {',
'  flex: 1;',
'  padding: 16px 20px;',
'}',
'',
'.summary-item + .summary-item {',
'  border-left: 1px solid #D4D8E2;;',
'}',
'',
'.summary-item label {',
'    font-family: Helvetica;',
'font-weight: 400;',
'font-style: Regular;',
'font-size: 16px;',
'leading-trim: NONE;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #7A7A7A;',
' display: block;',
'  margin-bottom: 10px;',
'}',
'',
'.summary-item p {',
'font-family: Helvetica;',
'font-weight: 700;',
'font-style: Bold;',
'font-size: 16px;',
'leading-trim: NONE;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #32373B;',
'}',
'',
'.upper-header{',
'    display: flex;',
'    justify-content: space-between;',
'    align-items: center;',
'    text-align: center;',
'    margin: 20px 0px;',
'}',
'',
'.pagination-ellipsis {',
'  display: inline-block;',
'  padding: 8px 12px;',
'  margin: 0 4px;',
'  background-color: #e0e0e0; /* Match button background */',
'  color: #888;',
'  border-radius: 6px;',
'  font-weight: bold;',
'  min-width: 32px;',
'  text-align: center;',
'  font-family: Arial, sans-serif;',
'}',
'',
'.cancel-loan {',
'  background-color: #e74c3c;',
'  color: white;',
'  border: none;',
'  padding: 8px 16px;',
'  border-radius: 4px;',
'  cursor: pointer;',
'  transition: background-color 0.3s ease;',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-style: Regular;',
'font-size: 14px;',
'leading-trim: NONE;',
'line-height: 100%;',
'letter-spacing: 0%;',
'}',
'',
'.cancel-loan:hover {',
'  background-color: #c0392b;',
'}',
'',
'h2{',
'    margin: 0px;',
'}',
'/*Company image and name*/',
'.internal-flex{',
'  display: flex;',
'  flex-wrap: wrap;',
'  align-items:center;',
'  margin: 20px 0;',
'}',
'',
'.img-div{',
'    padding: 4px;',
'    width: 48px;         /* Set the width of the div */',
'    height: 48px;       /* Set the height of the div */',
'    overflow: hidden; ',
'    margin-right:16px;',
'    border-radius: 4px;',
'    opacity: 0px;',
'    border: 1px solid #DDDDDD;',
'    position: relative;',
'}',
'',
'.prod-img{',
'   width: 100%;         /* Ensures the image width is 100% of the div */',
'    height: 100%;        /* Ensures the image height is 100% of the div */',
'    object-fit: cover;   /* The image will cover the div while maintaining its aspect ratio */',
'     max-width: 100%;  /* Image will never exceed the width of its container */',
'     box-sizing: border-box; /* Ensures padding is taken into account */',
'}',
'',
'.container{',
'   margin: 10px auto;',
'}',
'',
'.text-set p{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 20px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'text-transform: capitalize;',
'color: #423B3B;',
'}',
'',
'/**Tabs styling**/',
'.t-Tabs{',
'    border-bottom: 1px solid #E5E5E5;',
'}',
'',
'.t-Body .t-Tabs--simple .t-Tabs-link{',
'        color:#7A7A7A;',
'        text-decoration: none;',
'        font-family: Helvetica;',
'        font-weight: 400;',
'        font-size: 14px;',
'        line-height: 100%;',
'        letter-spacing: 0%;',
'        text-align: center;',
'}',
'',
'/** Company Description **/',
'.description-header{',
'    font-family: Helvetica;',
'    font-size: 18px;',
'    font-weight: 700;',
'    line-height: 24px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none; ',
'    width: Fill (531px)px;',
'    height: Fixed (48px)px;',
'    padding: 8px 0px 0px 0px;',
'    gap: 8px;',
'    border-radius: 4px 0px 0px 0px;',
'    opacity: 0px;',
'    color: #423B3B;',
'}',
'',
'/**Edit Button **/',
'',
'.edit-button {',
'  display: inline-flex;',
'  align-items: center;',
'  padding: 16px 16px 16px 0px;',
'  background-color: white;',
'  margin: 20px 0px 5px 0px;',
'  color: #1e90ff;',
'  border: none;',
'  font-size: 14px;',
'  font-weight: 500;',
'  border-radius: 4px;',
'  cursor: pointer;',
'  transition: 0.3s;',
'}',
'',
'.edit-button .icon {',
'  width: 16px;',
'  height: 16px;',
'  margin-right: 6px;',
'  filter: invert(37%) sepia(95%) saturate(1354%) hue-rotate(189deg) brightness(95%) contrast(101%);',
'}',
'',
'/*.edit-button:hover {',
'  background-color: #e6f3ff;',
'}*/',
'',
'',
'/*Products table css*/',
'',
'.controls {',
'  display: flex;',
'  flex-wrap: wrap;',
'  gap: 24px;',
'  justify-content: space-between;',
'  align-items: center;',
'  text-align: center;',
'  margin: 25px auto;',
'',
'}',
'',
'.controls h2{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 18px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #32373B;',
'}',
'',
'.sort-btn{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'  padding: 10px 14px;',
'  border: none;',
'  border-radius: 4px;',
'  cursor: pointer;',
'}',
'',
'.add-btn {',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 16px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'text-transform: capitalize;',
'  padding: 10px 14px;',
'  border: none;',
'  border-radius: 4px;',
'  cursor: pointer;',
'  background: #348BEF;',
'}',
'',
'.sort-btn {',
'  background-color: #f2f2f2;',
'}',
'',
'.add-btn {',
'  background-color: #007bff;',
'  color: #fff;',
'}',
'',
'.table-wrapper {',
'  overflow-x: auto;',
'}',
'',
'table {',
'  width: 100%;',
'  border-collapse: collapse;',
'  margin-bottom: 20px;',
'  min-width: 800px;',
'}',
'',
'thead {',
'  background-color:#2C2E2F;',
'  color: white;',
'}',
'',
'th{',
'  padding: 12px;',
'  text-align: left;',
'  border-bottom: 1px solid #ddd;',
'  white-space: nowrap;',
'  font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #F6F7F9;',
'}',
'',
'td {',
'  padding: 12px;',
'  text-align: left;',
'  border-bottom: 1px solid #ddd;',
'  white-space: nowrap;',
'  font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #7A7A7A; ',
'}',
'',
'.status {',
'  padding: 4px 10px;',
'  border-radius: 10px;',
'  font-size: 0.9em;',
'  display: inline-block;',
'}',
'',
'.status.Unpaid {',
'  background-color: #FDF6E2;',
'  color: #E1A90E;',
';',
'}',
'',
'.status.Paid {',
'  background-color: #F0FBEE;',
'  color: #3DB22A;',
';',
'}',
'',
'.pagination {',
'  display: flex;',
'  flex-wrap: wrap;',
'  gap: 10px;',
'  align-items: center;',
'  justify-content: space-between;',
'  padding: 30px 24px;',
'}',
'',
'.pagination select {',
'  padding: 5px;',
'  width: 81;',
'height: 40;',
'left: 91px;',
'opacity: 0.4;',
'border-radius: 6px;',
'font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #0C0C0C;',
'}',
'',
'.pagination span{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'/* color: #0C0C0C; */',
'}',
'',
'.page-buttons {',
'  display: flex;',
'  gap: 5px;',
'  flex-wrap: wrap;',
'}',
'',
'.page-buttons button {',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'line-height: 16px;',
'letter-spacing: 0%;',
'gap: 8px;',
'width: 40;',
'height: 40;',
'padding-top: 12px;',
'padding-right: 16px;',
'padding-bottom: 12px;',
'padding-left: 16px;',
'border-radius: 4px;',
'background: #E2E2E2;',
'color: #ABB3C5;',
'border:none;',
'}',
'',
'.page-buttons .active-page {',
'  /* background-color: #333;',
'  color: white;',
'  font-weight: bold; */',
' font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'line-height: 16px;',
'letter-spacing: 0%;',
'color: #2D416F;',
'border: none;',
'}',
'',
'@media (max-width: 768px) {',
'  .controls {',
'    flex-direction: column;',
'    align-items: stretch;',
'  }',
'',
'  .sort-btn,',
'  .add-btn {',
'    width: 100%;',
'  }',
'',
'  .pagination {',
'    flex-direction: column;',
'    align-items: flex-start;',
'  }',
'',
'  table {',
'    font-size: 14px;',
'  }',
'}',
'',
'',
'.t-Body .t-Tabs--simple .t-Tabs-link{',
'    border-top: 1px solid #ddd;',
'}',
'',
'',
'.ui-dialog-titlebar{',
'    align-items: center;',
'    text-align: center;',
'} ',
'',
'/** Ratings and Recommendations **/',
'',
'.ratings-card {',
'  /* border-radius: 1.25rem; */',
'  background-color: transparent; /* remove background */',
'  border-radius: 0;              /* remove rounded corners */',
'  box-sizing: border-box;',
'  box-shadow: none;              ',
'  border: none;',
'  padding: 1rem;',
'  margin: 1rem 0;',
'  width: 100%;',
'  max-width: 800px;',
'  /* box-sizing: border-box;',
'  box-shadow: 0 2px 6px rgba(0,0,0,0.05);  */',
'}',
'',
'.description {',
'    font-family: Helvetica;',
'    font-weight: 400;',
'    font-size: 16px;',
'    line-height: 150%;',
'    letter-spacing: 0%;',
'    color: #423B3B;',
'}',
'',
'.author {',
'  display: flex;',
'  align-items: center;',
'  background: #F7F7F7;',
'  border-radius: 30px;',
'}',
'',
'.avatar {',
'  width: 20px;',
'  height: 20px;',
'  border-radius: 50%;',
'  margin-right: 0.5rem;',
'  object-fit: cover;',
'}',
'',
'.name {',
'    font-family: Helvetica;',
'    font-weight: 400;',
'    font-size: 14px;',
'    line-height: 150%;',
'    letter-spacing: 0%;',
'    vertical-align: middle;',
'    text-transform: capitalize;',
'    color: #423B3B;',
'}',
'',
'.review-section {',
'  font-family: Helvetica;',
'  margin: 10px auto; ',
'  padding: 10px;  ',
'',
'}',
'',
'.review-box {',
'  /* background-color: #f9f9f9; */',
'  border-radius: 8px;',
'  /* padding: 15px; */',
'  margin-top: 10px;',
'}',
'',
'.review-title{',
'      display: flex;',
'  justify-content: space-between;',
'  align-items: center;',
'}',
'',
'.review-actions {',
'  display: flex;',
'  gap: 10px;',
'}',
'',
'.action-btn {',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'  border: none;',
'  padding: 5px 10px;',
'  border-radius: 4px;',
'  cursor: pointer;',
'}',
'',
'.action-btn.edit {',
'  background-color: #007bff;',
'  color: white;',
'}',
'',
'.action-btn.delete {',
'  background-color: #dc3545;',
'  color: white;',
'}',
'',
'.action-btn:hover {',
'  opacity: 0.85;',
'}',
'',
'.review-box strong{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 16px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'color: #423B3B;',
'}',
'',
'.review-box p {',
'  margin: 10px 0;',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'color: #423B3B;',
'}',
'',
'.reviewer {',
'  display: flex;',
'  align-items: center;',
'  margin-top: 10px;',
'  background: #F7F7F7;',
'  border-radius: 30px;',
'gap: 6px;',
'padding-top: 4px;',
'padding-right: 8px;',
'padding-bottom: 4px;',
'padding-left: 8px;',
'',
'}',
'',
'.reviewer-photo {',
'  width: 20px;',
'  height: 20px;',
'  border-radius: 50%;',
'  margin-right: 8px;',
'}',
'',
'.reviewer-name {',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 12px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'vertical-align: middle;',
'text-transform: capitalize;',
'color: #423B3B;',
'}',
'',
'.review-button {',
'  float: right;',
'  background-color: #007bff;',
'  color: white;',
'  border: none;',
'  padding: 8px 14px;',
'  border-radius: 5px;',
'  cursor: pointer;',
'  /* margin-top: 15px; */',
'}',
'',
'.review-button:hover {',
'  background-color: #0056b3;',
'}',
'',
'.review-header {',
'  display: flex;',
'  justify-content: space-between;',
'  align-items: center;',
'  text-align: center;',
'  margin-bottom: 15px;',
'}',
'',
'.review-header h3{',
'    font-family: Helvetica;',
'    font-weight: 700;',
'    font-size: 18px;',
'    line-height: 100%;',
'    letter-spacing: 0%;',
'    color: #32373B;',
'    margin: 0;',
'}',
'',
'/* Responsive tweaks */',
'@media (max-width: 600px) {',
'  .description {',
'    font-size: 16px;;',
'  }',
'',
'  .name {',
'    font-size: 14px;',
'  }',
'',
'  .avatar {',
'    width: 1.75rem;',
'    height: 1.75rem;',
'  }',
'}',
'',
'/* Responsive rule */',
'@media (max-width: 600px) {',
'  .review-header {',
'    flex-direction: column;',
'    align-items: flex-start;',
'  }',
'',
'  .review-button {',
'    align-self: flex-start;',
'  }',
'}',
'',
'ul{',
'    font-family: Helvetica;',
'font-weight: 400;',
'font-size: 16px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'text-transform: capitalize;',
'color: #7A7A7A;',
'}',
'',
'.comp-desc{',
'        font-family: Helvetica;',
'font-weight: 400;',
'font-size: 16px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'color: #7A7A7A;',
'}',
'',
'.a-AlertMessage{',
'    padding: 20px;',
'}',
'',
'.a-AlertMessage-icon{',
'    background-color: #D0E4FB;',
'    padding: 10px;',
'}',
'',
'.a-AlertMessage-title{',
'    font-family: Helvetica;',
'}',
'',
'.a-AlertMessage-details{',
'      font-family: Helvetica;',
'}',
'js-confirmBtn ui-button ui-corner-all ui-widget ui-button--hot{',
'    font-family: Helvetica;',
'}',
'',
'.t-Form--stretchInputs .t-Form-item {',
'  border-right: 1px solid #e1e1e1;',
'  padding-right: 20px;',
'}',
'.t-Form--stretchInputs .t-Form-item:last-child {',
'  border-right: none;',
'  padding-left: 20px;',
'}',
'',
'.loan-summary-box {',
'  display: flex;',
'  justify-content: space-between;',
'  border: 1px solid #eee;',
'  padding: 16px;',
'  border-radius: 8px;',
'  margin-bottom: 10px;',
'}',
'.loan-summary-box div {',
'  flex: 1;',
'}',
'.loan-summary-box div + div {',
'  border-left: 1px solid #ccc;',
'  padding-left: 8px;',
'}',
'.loan-summary-box p {',
'  margin: 0;',
'}',
'.loan-summary-box .label {',
'  color: #6c757d;',
'}',
'.loan-summary-box .value {',
'  font-weight: bold;',
'}',
''))
,p_page_template_options=>'#DEFAULT#'
,p_page_component_map=>'25'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(75776769949656739)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(2487513223224052)
,p_plug_display_sequence=>30
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_repayment_period   VARCHAR2(100);',
'    v_amount_borrowed    NUMBER;',
'    v_status             varchar2(100);',
'BEGIN',
'    SELECT duration, loan_amount, loan_status',
'    INTO v_repayment_period, v_amount_borrowed, v_status',
'    FROM XXMRKT.XXMRKT_APPLIED_LOANS',
'    WHERE loan_id = :P77_LOAN_ID;',
'  htp.p(',
'        ''<div class="upper-header">',
'            <div class="top-region-header"> ',
'                <button class="icon-button" onclick="return redirectToMainPageFunc(66)">',
'                          <img src="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/svgs/solid/arrow-left.svg" alt="Left Arrow" width="24" height="24" class="icon">',
'                          <span class="button-text">Back</span>',
'                </button>',
'                <p>Repayment Details</p>',
'            </div>',
'            <div>'');',
'            IF upper(v_status) = ''INITIATED'' THEN',
'               htp.p(''<button class="cancel-loan" onclick="return confirmCancelLoan()" id="cancel">Cancel Loan</button>'');',
'            END IF;',
'           htp.p(''</div>',
'        </div>',
'        <div class="loan-header">',
'              <div class="summary-item">',
'                <label>Repayment Period</label>',
'                <p>''||v_repayment_period||'' Months</p>',
'              </div>',
'              <div class="summary-item">',
'                <label>Amount Borrowed</label>',
unistr('                <p>\20A6''||TO_CHAR(v_amount_borrowed, ''FM999G999G999D00'')||''</p>'),
'              </div>',
'        </div>'');',
'    RETURN NULL;',
'EXCEPTION',
'    WHEN OTHERS THEN ',
'        NULL;',
'END;'))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(124419253750138592)
,p_plug_name=>'MarketPlace'
,p_icon_css_classes=>'fa-ai-sparkle-generate-list'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(2504366637224064)
,p_plug_display_sequence=>20
,p_location=>null
,p_menu_id=>wwv_flow_imp.id(2462480760224025)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_imp.id(2562100272224107)
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(168464722899912454)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#:t-TabsRegion-mod--simple'
,p_plug_template=>wwv_flow_imp.id(2515855534224073)
,p_plug_display_sequence=>60
,p_location=>null
,p_ai_enabled=>false
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(168465823406912465)
,p_plug_name=>'Repayment'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(2487513223224052)
,p_plug_display_sequence=>50
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_comp_type    VARCHAR2(100);',
'    v_type         NUMBER; -- 1 is for loan services',
'    v_count        NUMBER;',
'    v_offset       NUMBER;',
'    v_page_size    NUMBER := 5;',
'    v_process      VARCHAR2(200) := ''''''GET_REPAYMENT_DATA'''''';',
'    v_item         VARCHAR2(100) := ''''''P77_REP_OFFSET'''''';',
'    v_region         VARCHAR2(100) := ''''''repayment'''''';',
'    v_last_shown    NUMBER := 0;',
'BEGIN',
'',
'    BEGIN',
'        v_offset := TO_NUMBER(:P77_REP_OFFSET);',
'    EXCEPTION',
'        WHEN VALUE_ERROR THEN',
'            v_offset := 1;',
'    END;',
'    -- Get company type',
'    BEGIN',
'        SELECT COMPANY_TYPE',
'          INTO v_comp_type',
'          FROM XXMRKT.XXMRKT_COMPANY_LIST',
'         WHERE COMPANY_ID = :P77_COMPANY_ID;',
'    EXCEPTION',
'        WHEN NO_DATA_FOUND THEN',
'            NULL;',
'    END;',
'',
'    -- Count users for pagination',
'    SELECT CEIL(COUNT(*) / v_page_size)',
'      INTO v_count',
'    from XXMRKT.XXMRKT_APPLIED_LOANS_VIEW',
'       where loan_id = :p77_loan_id',
'       and company_code = :ap_company_code',
'       and company_id = :p77_company_id',
'       and staff_id = :ap_staff_id;',
'',
'    -- Render HTML if company type is Loan Services',
'    IF v_comp_type = ''Loan Services'' THEN',
'        v_type := 1;',
'',
'        IF v_offset < 1 THEN',
'            v_offset := 1;',
'        ELSIF v_offset > v_count THEN',
'            v_offset := v_count;',
'        END IF;',
'                        -- Begin HTML Output',
'        htp.p(''',
'              <div class="controls">',
'				<h2>Loan Repayment History</h2>',
'				<div>',
'				<input type="text" id="repayments-search" placeholder="Search repayment..." onkeyup="filterRepayments()" class="search-input">',
'				</div>',
'			  </div>',
'',
'			  <div class="table-wrapper">',
'				<table>',
'				  <thead>',
'					<tr>',
'					  <th>Period</th>',
'					  <th>Repayment Date</th>',
'					  <th>Repayment Amount</th>',
'					  <th>Status</th>',
'					</tr>',
'				  </thead>',
'				  <tbody id="rep-table-body">',
'					<!-- Dynamic rows go here -->',
'				  </tbody>',
'				</table>',
'			  </div>'');',
'                    -- Pagination Controls',
'                    htp.p(''<div class="pagination">',
'              <div class="showing">',
'                <span>Showing</span>',
'                <select id="repayment-select" onchange="handlePageChange(this,''|| v_process || '', '' || v_item || '', ''||v_region||'','' || v_count || '')">'');',
'',
'                    FOR i IN 1..v_count LOOP',
'                        IF i = v_offset THEN',
'                            htp.p(''<option value="'' || i || ''" selected>'' || i || ''</option>'');',
'                        ELSE',
'                            htp.p(''<option value="'' || i || ''">'' || i || ''</option>'');',
'                        END IF;',
'                    END LOOP;',
'',
'                    htp.p(''</select>',
'                        <span>out of <span id="total-pages">'' || v_count || ''</span></span>',
'                      </div>',
'',
'                      <div class="page-buttons">',
'                        <button id="prev" onclick="return apprPaginate(-1,'' || v_process || '', '' || v_item || '', '' || v_region || '','' || v_count || '')">&lt;</button>'');',
'',
'                            FOR i IN 1..v_count LOOP',
'                                                                            -- Show first, last, current, and one before/after current',
'                                IF i = 1 OR i = v_count OR i = v_offset OR i = v_offset - 1 OR i = v_offset + 1 THEN',
'                                  ',
'                                  -- If there is a gap between last shown and current, add ellipsis',
'                                  IF v_last_shown <> 0 AND i > v_last_shown + 1 THEN',
'                                    htp.p(''<span class="pagination-ellipsis">...</span>'');',
'                                  END IF;',
'',
'                                  -- Render button',
'                                  htp.p(''<button onclick="return getData('' || i || '', '' || v_process || '', '' || v_region || '')">'' || i || ''</button>'');',
'                                  v_last_shown := i;',
'',
'                                END IF;',
'                            END LOOP;',
'',
'                            htp.p(''<button onclick="return apprPaginate(1, '' || v_process || '', '' || v_item || '', '' || v_region || '','' || v_count || '')">&gt;</button>',
'                    </div>'');',
'',
'                    -- Close Wrapper',
'                    htp.p(''</div>',
'            '');',
'',
'        RETURN NULL;',
'    END IF;',
'EXCEPTION',
'    WHEN OTHERS THEN ',
'         null;',
'END;',
''))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(74165346405954935)
,p_name=>'P77_LOAN_ID'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_imp.id(168464722899912454)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(75567608400060745)
,p_name=>'P77_PRODUCT_ID'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_imp.id(168464722899912454)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(75567713030060746)
,p_name=>'P77_HEADER'
,p_item_sequence=>50
,p_item_plug_id=>wwv_flow_imp.id(168464722899912454)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(75776631568656738)
,p_name=>'P77_CONTROL'
,p_item_sequence=>60
,p_item_plug_id=>wwv_flow_imp.id(168464722899912454)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(75776841700656740)
,p_name=>'P77_REP_OFFSET'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_imp.id(168464722899912454)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(168471578187912517)
,p_name=>'P77_COMPANY_ID'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(168464722899912454)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(74824627711709294)
,p_name=>'New'
,p_event_sequence=>10
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'ready'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(74825197364709294)
,p_event_id=>wwv_flow_imp.id(74824627711709294)
,p_event_result=>'TRUE'
,p_action_sequence=>20
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'apex.util.getTopApex().jQuery(".modal-dialog--pullout .ui-dialog-title").prepend(''<img src="#APP_IMAGES#Featured icon.png" style="height:48px;"/>'');'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(74823456042709293)
,p_process_sequence=>10
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'PROCESS_DATA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    V_ROW XXMRKT.XXMRKT_APPLIED_LOANS%ROWTYPE;',
'BEGIN',
' SELECT *',
' INTO V_ROW',
' FROM XXMRKT.XXMRKT_APPLIED_LOANS',
' WHERE LOAN_ID = :P77_LOAN_ID',
' AND COMPANY_ID = :P77_COMPANY_ID',
' AND PRODUCT_ID = :P77_PRODUCT_ID',
' AND COMPANY_CODE = :AP_COMPANY_CODE;',
'',
' v_row.LOAN_STATUS := ''CANCELLED'';',
' v_row.UPDATED_BY := :AP_USER_ID;',
' v_row.UPDATE_DATE := SYSDATE;',
'',
' XXMRKT.XXMRKT_APPLIED_LOANS_API.update_row (',
'    p_row => v_row );',
'    --before update loan_status ',
'UPDATE XXMRKT.XXMRKT_LOAN_STATUS ',
'SET STATUS = ''CANCELLED''',
'WHERE loan_id = :P77_LOAN_ID',
'AND COMPANY_ID = :P77_COMPANY_ID',
'AND COMPANY_CODE = :AP_COMPANY_CODE;',
'',
'COMMIT;',
'    APEX_JSON.OPEN_OBJECT;',
'    APEX_JSON.WRITE(''status'', ''success'');',
'    APEX_JSON.CLOSE_OBJECT;',
'EXCEPTION',
'    WHEN OTHERS THEN',
'        APEX_JSON.OPEN_OBJECT;',
'        APEX_JSON.WRITE(''status'', ''failed'');',
'        APEX_JSON.CLOSE_OBJECT;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>74823456042709293
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(74823851802709293)
,p_process_sequence=>20
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GET_DATA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'BEGIN',
'  -- Open JSON array',
'  apex_json.open_array;',
'',
'  FOR pro_rec IN (',
'    SELECT B.PRODUCT_NAME,',
'       C.LOAN_TYPE,',
'       B.INTEREST_RATE,',
'       A.LOAN_aMOUNT,',
'       A.DURATION,',
'       A.START_DATE,',
'       A.END_dATE,',
'       A.LOAN_STATUS',
'    FROM XXMRKT.XXMRKT_APPLIED_LOANS A, XXMRKT.XXMRKT_PRODUCT_LIST B, XXMRKT.XXMRKT_LOAN_TYPES C',
'    WHERE A.COMPANY_ID = 4--APEX_APPLICATION.g_x01',
'    AND A.COMPANY_CODE = :AP_COMPANY_CODE',
'    AND A.PRODUCT_ID = B.PRODUCT_ID',
'    AND A.CREATED_BY = :AP_STAFF_ID',
'    AND B.PRODUCT_TYPE = C.LOAN_TYPE_ID',
'    ORDER BY A.CREATION_DATE DESC',
'  )',
'  LOOP',
'    apex_json.open_object;',
'    apex_json.write(''loanName'', pro_rec.product_name);',
'    apex_json.write(''loanType'', pro_rec.loan_type);',
'    apex_json.write(''interestRate'', pro_rec.interest_rate);',
'    apex_json.write(''loanAmount'', pro_rec.loan_amount);',
'    apex_json.write(''loanDuration'', pro_rec.duration);',
'    apex_json.write(''startDate'', pro_rec.start_date);',
'    apex_json.write(''endDate'', pro_rec.end_date);',
'    apex_json.write(''loanStatus'', pro_rec.loan_status);',
'    apex_json.close_object;',
'  END LOOP;',
'',
'  apex_json.close_array;',
'',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    -- Clear previous output (if any)',
'    apex_json.free_output;',
'    ',
'    -- Start fresh JSON error response',
'    apex_json.open_object;',
'    apex_json.write(''status'', ''error'');',
'    apex_json.write(''message'', SQLERRM);',
'    apex_json.close_object;',
'',
'    -- RAISE_APPLICATION_ERROR is optional here; use it to signal error to JavaScript',
'    -- raise_application_error(-20001, SQLERRM);',
'END;',
'',
'',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>74823851802709293
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(74824299238709293)
,p_process_sequence=>30
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GET_LOAN_HIST_DATA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'BEGIN',
'  -- Open JSON array',
'  apex_json.open_array;',
'',
'  FOR pro_rec IN (',
'    SELECT B.PRODUCT_NAME,',
'       C.LOAN_TYPE,',
'       B.INTEREST_RATE,',
'       A.LOAN_aMOUNT,',
'       A.DURATION,',
'       A.START_DATE,',
'       A.END_dATE,',
'       A.LOAN_STATUS',
'    FROM XXMRKT.XXMRKT_APPLIED_LOANS A, XXMRKT.XXMRKT_PRODUCT_LIST B, XXMRKT.XXMRKT_LOAN_TYPES C',
'    WHERE A.COMPANY_ID = 4--APEX_APPLICATION.g_x01',
'    AND A.COMPANY_CODE = :AP_COMPANY_CODE',
'    AND A.PRODUCT_ID = B.PRODUCT_ID',
'    AND A.CREATED_BY = :AP_STAFF_ID',
'    AND B.PRODUCT_TYPE = C.LOAN_TYPE_ID',
'    ORDER BY A.CREATION_DATE DESC',
'  )',
'  LOOP',
'    apex_json.open_object;',
'    apex_json.write(''loanName'', pro_rec.product_name);',
'    apex_json.write(''loanType'', pro_rec.loan_type);',
'    apex_json.write(''interestRate'', pro_rec.interest_rate);',
'    apex_json.write(''loanAmount'', pro_rec.loan_amount);',
'    apex_json.write(''loanDuration'', pro_rec.duration);',
'    apex_json.write(''startDate'', pro_rec.start_date);',
'    apex_json.write(''endDate'', pro_rec.end_date);',
'    apex_json.write(''loanStatus'', pro_rec.loan_status);',
'    apex_json.close_object;',
'  END LOOP;',
'',
'  apex_json.close_array;',
'',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    -- Clear previous output (if any)',
'    apex_json.free_output;',
'    ',
'    -- Start fresh JSON error response',
'    apex_json.open_object;',
'    apex_json.write(''status'', ''error'');',
'    apex_json.write(''message'', SQLERRM);',
'    apex_json.close_object;',
'',
'    -- RAISE_APPLICATION_ERROR is optional here; use it to signal error to JavaScript',
'    -- raise_application_error(-20001, SQLERRM);',
'END;',
'',
'',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>74824299238709293
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(75568021699060749)
,p_process_sequence=>40
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GET_REPAYMENT_DATA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE ',
'    v_page_size NUMBER := 7;',
'BEGIN ',
'   :P77_REP_OFFSET := apex_application.g_x02;',
'',
'   -- Open JSON array',
'   apex_json.open_array;',
'',
'   FOR pro_rec IN (',
'       SELECT ',
'         period, ',
'         round(repayment_amount, 2) repayment_amount, ',
'         status, ',
'         repayment_date ',
'       FROM XXMRKT.XXMRKT_APPLIED_LOANS_VIEW',
'       WHERE loan_id = :P77_LOAN_ID',
'         AND company_id = :P77_COMPANY_ID',
'         ORDER BY START_DATE ASC',
'   )',
'   LOOP',
'      apex_json.open_object; ',
'      apex_json.write(''period'', INITCAP(pro_rec.period));',
'      apex_json.write(''repayment_amount'', pro_rec.repayment_amount); ',
'      apex_json.write(''status'', INITCAP(pro_rec.status));',
'      apex_json.write(''repayment_date'', nvl(TO_CHAR(pro_rec.repayment_date, ''YYYY-MM-DD''), ''N/A'')); ',
'      apex_json.close_object;',
'   END LOOP;',
'',
'   apex_json.close_array;',
'  ',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    apex_json.free_output;',
'    apex_json.open_object;',
'    apex_json.write(''status'', ''error'');',
'    apex_json.write(''message'', SQLERRM);',
'    apex_json.close_object;',
'END;',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>75568021699060749
);
wwv_flow_imp.component_end;
end;
/
