prompt --application/pages/page_00068
begin
--   Manifest
--     PAGE: 00068
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>3780766536418114
,p_default_application_id=>2000004
,p_default_id_offset=>0
,p_default_owner=>'XXSBS'
);
wwv_flow_imp_page.create_page(
 p_id=>68
,p_name=>'Marketplace Product Details'
,p_alias=>'PK66'
,p_step_title=>'Marketplace Product Details'
,p_autocomplete_on_off=>'OFF'
,p_javascript_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/**Products JS */',
'/**',
' * Dynamic Product Table with Pagination',
' * -------------------------------------',
' * Extend `productData` with your own records.',
' */',
'',
'let productData = [];',
'',
'const getData = (offset, process, type) => {',
'  apex.server.process(process, {',
'    x01: $v(''P68_COMPANY_ID''),',
'    x02: offset',
'  }, {',
'    dataType: "json",',
'    success: function(data) {',
'        // if(type === ''users''){',
'        //     usersData = [...data];',
'        //     renderUsersTablePage(offset);',
'        //       const select = document.getElementById(`${type}-select`);',
'        //         if (select) {',
'        //             select.value = offset;',
'        //         }',
'        // }',
'        if(type === ''products''){',
'            productData = [...data];  ',
'            renderTablePage(offset);',
'        }',
'        // if(type === ''approvers''){',
'        //     approversData = [...data];',
'        //     renderApproversTablePage(offset);',
'        // }',
'        const select = document.getElementById(`${type}-select`);',
'            if (select) {',
'                select.value = offset;',
'        }',
'    },',
'    error: function(jqXHR, textStatus, errorThrown) {',
'      console.error("Error loading product data:", textStatus, errorThrown);',
'    }',
'  });',
'  return false;',
'};',
'',
'',
'// console.log(productData);',
'',
'const rowsPerPage = 4;',
'let currentPage = 1;',
'let currentSortKey = "";',
'let sortAscending = true;',
'',
'const tableBody = document.getElementById("product-table-body");',
'const paginationContainer = document.querySelector(".page-buttons");',
'const pageSelector = document.getElementById("page-select");',
'const totalPagesSpan = document.getElementById("total-pages");',
' const loanTableBody = document.getElementById("loan-table-body");',
'',
'',
'function getTotalPages() {',
'  return Math.ceil(productData.length / rowsPerPage);',
'}',
'',
'function renderTablePage(page) {',
'  tableBody.innerHTML = "";',
'',
'  const start = (page - 1) * rowsPerPage;',
'  const end = start + rowsPerPage;',
'  const pageData = productData.slice(start, end);',
'',
'  pageData.forEach(item => {',
'    const row = document.createElement("tr");',
'    row.innerHTML = `',
'      <td>${item.productName}</td>',
'      <td>${item.productType}</td>',
'      <td>${item.interestRate}</td>',
'      <td>${item.chargesType === ''%''? item.charges + item.chargesType: item.chargesType + item.charges }</td>',
'      <td>${item.insuranceFeesType === ''%''? item.insuranceFees + item.insuranceFeesType: item.insuranceFeesType + item.insuranceFees }</td>',
'      <td><a href="#" style="text-decoration:none; color: #7A7A7A; font:Helvetica; font-weight:700; font-size: 14px;" onclick="return redirectToModalPage71ApplyForLoan(71, ${item.companyID}, ${item.productID}, ''Apply for ${item.productType} '')">Apply'
||unistr(' for loan \2197</a></td>'),
'    `;',
'    tableBody.appendChild(row);',
'  });',
'',
'//   renderPagination();',
'}',
'',
'// function renderPagination() {',
'//   const totalPages = getTotalPages();',
'//   paginationContainer.innerHTML = "";',
'',
'//   // Prev Button',
'//   const prevBtn = document.createElement("button");',
'//   prevBtn.textContent = "<";',
'//   prevBtn.disabled = currentPage === 1;',
'//   prevBtn.onclick = () => {',
'//     currentPage--;',
'//     renderTablePage(currentPage);',
'//     renderLoanTablePage(currentPage);',
'//   };',
'//   paginationContainer.appendChild(prevBtn);',
'',
'//   // Page Buttons',
'//   for (let i = 1; i <= totalPages; i++) {',
'//     const pageBtn = document.createElement("button");',
'//     pageBtn.textContent = i;',
'//     pageBtn.className = i === currentPage ? "active-page" : "";',
'//     pageBtn.onclick = () => {',
'//       currentPage = i;',
'//       renderTablePage(currentPage);',
'//       renderLoanTablePage(currentPage);',
'//     };',
'//     paginationContainer.appendChild(pageBtn);',
'//   }',
'',
'//   // Next Button',
'//   const nextBtn = document.createElement("button");',
'//   nextBtn.textContent = ">";',
'//   nextBtn.disabled = currentPage === totalPages;',
'//   nextBtn.onclick = () => {',
'//     currentPage++;',
'//     renderTablePage(currentPage);',
'//     renderLoanTablePage(currentPage);',
'//   };',
'//   paginationContainer.appendChild(nextBtn);',
'',
'//   // Update dropdown',
'//   pageSelector.innerHTML = "";',
'//   for (let i = 1; i <= totalPages; i++) {',
'//     const opt = document.createElement("option");',
'//     opt.value = i;',
'//     opt.textContent = i;',
'//     if (i === currentPage) opt.selected = true;',
'//     pageSelector.appendChild(opt);',
'//   }',
'',
'//   // Update total pages display',
'//   totalPagesSpan.textContent = totalPages;',
'// }',
'',
'// // Dropdown change',
'// pageSelector.addEventListener("change", function () {',
'//   currentPage = parseInt(this.value, 10);',
'//   renderTablePage(currentPage);',
'//   renderLoanTablePage(currentPage);',
'// });',
'',
'// // sort function',
'// const sortBtn = () => {',
'//   const sortKey = "loanName";',
'//   if (currentSortKey === sortKey) {',
'//     sortAscending = !sortAscending;',
'//   } else {',
'//     currentSortKey = sortKey;',
'//     sortAscending = true;',
'//   }',
'',
'//   productData.sort((a, b) => {',
'//     if (a[sortKey] < b[sortKey]) return sortAscending ? -1 : 1;',
'//     if (a[sortKey] > b[sortKey]) return sortAscending ? 1 : -1;',
'//     return 0;',
'//   });',
'',
'//   renderTablePage(currentPage);',
'//   renderLoanTablePage(currentPage);',
'',
'//    return false;',
'   ',
'// };',
'',
'// // Initial render',
'// renderTablePage(currentPage);',
'// renderLoanTablePage(currentPage);',
'',
'// Pagination Handler',
'function apprPaginate(direction, process, item, type, totalCount) {',
'  let current = parseInt($v(item)) || 0;',
'  //const pageSize = 1;',
'  let newOffset = current + (direction);',
'  if (newOffset < 1) newOffset = 1;',
'  if (newOffset > totalCount) newOffset = totalCount;',
'  $s(item, newOffset);',
'  getData(newOffset, process, type);',
'  return false;',
'}',
'',
'function handlePageChange(selectElement, process, item, type) {',
'  const selectedValue = parseInt(selectElement.value);',
'  console.log("Selected page:", selectedValue);',
'  $s(item, selectedValue);',
'  getData(selectedValue, process, type);',
'  return false;',
'}',
'// Code for Loan History',
'',
'let loanData = [];',
'const getLoanData = () => {',
'  apex.server.process("GET_LOAN_HIST_DATA", {',
'    x01: $v(''P68_COMPANY_ID'')',
'    },',
'    {',
'      dataType: "json",',
'      success: function(data) {',
'        loanData = [...data];        // Assign server data to global variable',
'        currentPage = 1;                // Reset to page 1',
'        renderLoanTablePage(currentPage);  // Call your existing render function',
'      },',
'      error: function(jqXHR, textStatus, errorThrown) {',
'        console.error("Error loading product data:", textStatus, errorThrown);',
'      }',
'    }',
'  );',
'}',
'',
'window.onload = getLoanData();',
'',
'console.log(loanData);',
'',
'function renderLoanTablePage(page) {',
'//   loanTableBody.innerHTML = "";',
'',
'//   const start = (page - 1) * rowsPerPage;',
'//   const end = start + rowsPerPage;',
'//   const loanPageData = loanData.slice(start, end);',
'',
'//   loanPageData.forEach(item => {',
'//     const row = document.createElement("tr");',
'//     row.innerHTML = `',
'//       <td>${item.productName}</td>',
'//       <td>${item.loanType}</td>',
'//       <td>${item.interestRate}</td>',
'//       <td>${item.loanAmount}</td>',
'//       <td>${item.duration}</td>',
'//       <td>${item.start_date}</td>',
'//       <td>${item.end_date}</td>',
'//       <td>${item.status}</td>',
unistr('//       <td><a href="#" style="text-decoration:none; color: #7A7A7A; font:Helvetica; font-weight:700; font-size: 14px;" onclick="return redirectToModalPage71ApplyForLoan(71, ${item.companyID}, ${item.productID})">Apply for loan \2197</a></td>'),
'//     `;',
'//     loanTableBody.appendChild(row);',
'//   });',
'',
'//   renderPagination();',
'}',
'',
'',
'var modal = document.getElementById(''main-modal'');',
'',
'',
'function afterLoad(){',
'    apex.message.showPageSuccess(''success'');',
'}',
'',
'const redirectToMainPageFunc = (pageID) => {',
'        var url = `f?p=#APP_ID#:${pageID}:#SESSION#::NO:RP,${pageID}:`;',
'        //var url = "f?p=#APP_ID#:"+''201''+":#SESSION#::NO:RP,201:";',
'        url = url.replace("#APP_ID#",&APP_ID.);',
'',
'        url = url.replace("#SESSION#", &SESSION.);',
'',
'        apex.server.process("PREPARE_URL", {',
'',
'                    x01: url',
'',
'        }, {',
'',
'        success: function(pData) {',
'',
'        if (pData.success === true) {',
'',
'                apex.navigation.redirect(pData.url);',
'',
'        } else {',
'',
'                console.log("FALSE");',
'',
'        }',
'',
'        },',
'',
'        error: function(request, status, error) {',
'',
unistr('               console.log("status\2014" + status + " error\2014-" + error);'),
'',
'        }',
'',
'    });',
'    ',
'    ',
'            return false;',
'        ',
'};',
'',
'',
'const redirectToModal = (pageID, compID) => {',
'        var url = `f?p=#APP_ID#:${pageID}:#SESSION#::NO:RP,${pageID}:P69_COMPANY_ID:${compID}`; //''f?p='' || l_app || '':''||apex_application.g_x01||'':''||l_session||''::NO::''||l_item_name||'':''||apex_application.g_x02,',
'        //var url = "f?p=#APP_ID#:"+''201''+":#SESSION#::NO:RP,201:";',
'        url = url.replace("#APP_ID#",&APP_ID.);',
'',
'        url = url.replace("#SESSION#", &SESSION.);',
'        ',
'        apex.server.process("PREPARE_URL", {',
'',
'                    x01: url',
'',
'        }, {',
'',
'        success: function(pData) {',
'',
'        if (pData.success === true) {',
'',
'                apex.navigation.redirect(pData.url);',
'',
'        } else {',
'',
'                console.log("FALSE");',
'',
'        }',
'',
'        },',
'',
'        error: function(request, status, error) {',
'',
unistr('               console.log("status\2014" + status + " error\2014-" + error);'),
'',
'        }',
'',
'    });',
'    ',
'    ',
'            return false;',
'        ',
'};',
'',
'',
'const redirectToModalPage69WriteAReview = (pageID, compID) => {',
'        var url = `f?p=#APP_ID#:${pageID}:#SESSION#::NO:RP,${pageID}:P69_COMPANY_ID:${compID}`; //''f?p='' || l_app || '':''||apex_application.g_x01||'':''||l_session||''::NO::''||l_item_name||'':''||apex_application.g_x02,',
'        //var url = "f?p=#APP_ID#:"+''201''+":#SESSION#::NO:RP,201:";',
'        url = url.replace("#APP_ID#",&APP_ID.);',
'',
'        url = url.replace("#SESSION#", &SESSION.);',
'        ',
'        apex.server.process("PREPARE_URL", {',
'',
'                    x01: url',
'',
'        }, {',
'',
'        success: function(pData) {',
'',
'        if (pData.success === true) {',
'',
'                apex.navigation.redirect(pData.url);',
'',
'        } else {',
'',
'                console.log("FALSE");',
'',
'        }',
'',
'        },',
'',
'        error: function(request, status, error) {',
'',
unistr('               console.log("status\2014" + status + " error\2014-" + error);'),
'',
'        }',
'',
'    });',
'    ',
'    ',
'            return false;',
'        ',
'};',
'',
'const redirectToModalPage69UpdateReview= (pageID, compID, reviewID) => {',
'        var url = `f?p=#APP_ID#:${pageID}:#SESSION#::NO:RP,${pageID}:P69_COMPANY_ID,P69_REVIEW_ID:${compID},${reviewID}`; //''f?p='' || l_app || '':''||apex_application.g_x01||'':''||l_session||''::NO::''||l_item_name||'':''||apex_application.g_x02,',
'        //var url = "f?p=#APP_ID#:"+''201''+":#SESSION#::NO:RP,201:";',
'        url = url.replace("#APP_ID#",&APP_ID.);',
'',
'        url = url.replace("#SESSION#", &SESSION.);',
'        ',
'        apex.server.process("PREPARE_URL", {',
'',
'                    x01: url',
'',
'        }, {',
'',
'        success: function(pData) {',
'',
'        if (pData.success === true) {',
'',
'                apex.navigation.redirect(pData.url);',
'',
'        } else {',
'',
'                console.log("FALSE");',
'',
'        }',
'',
'        },',
'',
'        error: function(request, status, error) {',
'',
unistr('               console.log("status\2014" + status + " error\2014-" + error);'),
'',
'        }',
'',
'    });',
'    ',
'    ',
'            return false;',
'        ',
'};',
'',
'function show_notification(Msg){',
'  apex.message.showPageSuccess(Msg);',
'                 $(''#t_Alert_Success'').attr(''style'',''background-color: #fffae5;'');',
'                 $(''.t-Alert-title'').attr(''style'',''color: black;font-weight: bold;'');',
'                 $(''#t_Alert_Success div div.t-Alert-icon span'').removeClass(''t-Icon'').addClass(''fa fa-exclamation-triangle fa-2x fa-anim-flash fam-x fam-is-danger'');',
'                 $(''#t_Alert_Success  div div.t-Alert-icon span'').attr(''style'',''color: #ffcc00'');',
'                 $(''div.t-Alert-buttons button.t-Button span.t-Icon'').css(''color'', ''#f00'');',
'}',
'',
'',
'function deleteReview(reviewID){',
'    apex.message.confirm( "Are you sure you want to delete this review?", function( okPressed ) {',
'        if( okPressed ) {',
'             apex.server.process("PROCESS_DATA", {',
'                x01: reviewID',
'                },',
'                {',
'                dataType: "text",',
'                success: function(data) {',
'                    //console.log(''successful'');',
'                    // location.reload();',
'                     $( "#rating" ).load(window.location.href + " #rating" );',
'                     //apex.region("$rating").refresh();',
'                     apex.message.showPageSuccess( ''Review Successfully Deleted'' )',
'                },',
'                error: function(jqXHR, textStatus, errorThrown) {',
'                    console.error("Error deleting review:", textStatus, errorThrown);',
'                }',
'                }',
'            );',
'        }',
'    },{',
'            title: "Warning!",',
'            style: "danger",',
'            dialogClasses: "my-custom-class",',
'            iconClasses: "fa fa-trash fa-2x",',
'            cancelLabel: "No",',
'            confirmLabel: "Yes, Delete Review",',
'        });',
'',
'    return false;',
'}',
'',
'function redirectToModalPage71ApplyForLoan(pageID, compID, productID, productType',
') {',
'        var url = `f?p=#APP_ID#:${pageID}:#SESSION#::NO:RP,${pageID}:P71_COMPANY_ID,P71_PRODUCT_ID,P71_HEADER,P71_CONTROL:${compID},${productID},${productType}, Select Repayment Period`; //''f?p='' || l_app || '':''||apex_application.g_x01||'':''||l_sessio'
||'n||''::NO::''||l_item_name||'':''||apex_application.g_x02,',
'        //var url = "f?p=#APP_ID#:"+''201''+":#SESSION#::NO:RP,201:";',
'        url = url.replace("#APP_ID#",&APP_ID.);',
'',
'        url = url.replace("#SESSION#", &SESSION.);',
'        ',
'        apex.server.process("PREPARE_URL", {',
'',
'                    x01: url',
'',
'        }, {',
'',
'        success: function(pData) {',
'',
'        if (pData.success === true) {',
'',
'                apex.navigation.redirect(pData.url);',
'',
'        } else {',
'',
'                console.log("FALSE");',
'',
'        }',
'',
'        },',
'',
'        error: function(request, status, error) {',
'',
unistr('               console.log("status\2014" + status + " error\2014-" + error);'),
'',
'        }',
'',
'    });',
'    ',
'    ',
'            return false;',
'        ',
'}',
'',
'function filterProducts() {',
'  const input = document.getElementById(''product-search'');',
'  const filter = input.value.toLowerCase();',
'  document.querySelectorAll(''#product-table-body tr'').forEach(row => {',
'    row.style.display = row.textContent.toLowerCase().includes(filter) ? '''' : ''none'';',
'  });',
'}',
'',
'window.onload = () => {',
'  getData(1, ''GET_DATA'', ''products'');',
'//   getData(1, ''GET_APPROVERS_DATA'', ''approvers'');',
'//   getData(1, ''GET_USER_DATA'', ''users'');',
'',
'  renderTablePage(currentPage);',
'//   renderApproversTablePage(currentPage);',
'//   renderUsersTablePage(currentPage);',
'};'))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/*Back Button*/',
'.icon-button {',
'  display: flex;',
'  align-items: center; /* Vertically center the icon and text */',
'  /* padding: 20px 0px; */',
'  background: #FFFFFF;',
'  color: #000000;',
'  border: none;',
'  border-radius: 5px;',
'  cursor: pointer;',
'  font-size: 16px;',
'  transition: background-color 0.3s;',
'  margin: 8px 0;',
'}',
'',
'',
'.icon {',
'  width: 20px; /* Set the width of the icon */',
'  height: 20px; /* Set the height of the icon */',
'  margin-right: 10px; /* Space between icon and text */',
'}',
'',
'',
'.button-text {',
'  white-space: nowrap; /* Prevent the text from breaking onto a new line */',
'    font-family: Helvetica;',
'    font-size: 16px;',
'    font-weight: 700;',
'    line-height: 18.4px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'}',
'',
'',
'/*Company image and name*/',
'.internal-flex{',
'  display: flex;',
'  flex-wrap: wrap;',
'  align-items:center;',
'  margin: 20px 0;',
'}',
'',
'.img-div{',
'    padding: 4px;',
'    width: 48px;         /* Set the width of the div */',
'    height: 48px;       /* Set the height of the div */',
'    overflow: hidden; ',
'    margin-right:16px;',
'    border-radius: 4px;',
'    opacity: 0px;',
'    border: 1px solid #DDDDDD;',
'    position: relative;',
'}',
'',
'.prod-img{',
'   width: 100%;         /* Ensures the image width is 100% of the div */',
'    height: 100%;        /* Ensures the image height is 100% of the div */',
'    object-fit: cover;   /* The image will cover the div while maintaining its aspect ratio */',
'     max-width: 100%;  /* Image will never exceed the width of its container */',
'     box-sizing: border-box; /* Ensures padding is taken into account */',
'}',
'',
'.container{',
'   margin: 10px auto;',
'}',
'',
'.search-input {',
'    padding: 8px 12px;',
'    border: 1px solid #ccc;',
'    border-radius: 4px;',
'    font-family: Helvetica;',
'    font-size: 14px;',
'    width: 200px;',
'}',
'',
'.text-set p{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 20px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'text-transform: capitalize;',
'color: #423B3B;',
'}',
'',
'.showing{',
'  display: flex;',
'  gap: 24px;',
'  align-items: center;',
'  margin: 0 24px;',
'}',
'/**Tabs styling**/',
'.t-Tabs{',
'    border-bottom: 1px solid #E5E5E5;',
'}',
'',
'.t-Body .t-Tabs--simple .t-Tabs-link{',
'        color:#7A7A7A;',
'        text-decoration: none;',
'        font-family: Helvetica;',
'        font-weight: 400;',
'        font-size: 14px;',
'        line-height: 100%;',
'        letter-spacing: 0%;',
'        text-align: center;',
'}',
'',
'/** Company Description **/',
'.description-header{',
'    font-family: Helvetica;',
'    font-size: 18px;',
'    font-weight: 700;',
'    line-height: 24px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none; ',
'    width: Fill (531px)px;',
'    height: Fixed (48px)px;',
'    padding: 8px 0px 0px 0px;',
'    gap: 8px;',
'    border-radius: 4px 0px 0px 0px;',
'    opacity: 0px;',
'    color: #423B3B;',
'}',
'',
'.pagination-ellipsis {',
'  display: inline-block;',
'  padding: 8px 12px;',
'  margin: 0 4px;',
'  background-color: #e0e0e0; /* Match button background */',
'  color: #888;',
'  border-radius: 6px;',
'  font-weight: bold;',
'  min-width: 32px;',
'  text-align: center;',
'  font-family: Arial, sans-serif;',
'}',
'',
'/**Edit Button **/',
'',
'.edit-button {',
'  display: inline-flex;',
'  align-items: center;',
'  padding: 16px 16px 16px 0px;',
'  background-color: white;',
'  margin: 20px 0px 5px 0px;',
'  color: #1e90ff;',
'  border: none;',
'  font-size: 14px;',
'  font-weight: 500;',
'  border-radius: 4px;',
'  cursor: pointer;',
'  transition: 0.3s;',
'}',
'',
'.edit-button .icon {',
'  width: 16px;',
'  height: 16px;',
'  margin-right: 6px;',
'  filter: invert(37%) sepia(95%) saturate(1354%) hue-rotate(189deg) brightness(95%) contrast(101%);',
'}',
'',
'/*.edit-button:hover {',
'  background-color: #e6f3ff;',
'}*/',
'',
'',
'/*Products table css*/',
'',
'.controls {',
'  display: flex;',
'  flex-wrap: wrap;',
'  gap: 10px;',
'  justify-content: space-between;',
'  align-items: center;',
'  text-align: center;',
'  margin: 10px auto;',
'',
'}',
'',
'.controls h2{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 18px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #32373B;',
'}',
'',
'.sort-btn{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'  padding: 10px 14px;',
'  border: none;',
'  border-radius: 4px;',
'  cursor: pointer;',
'}',
'',
'.add-btn {',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 16px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'text-transform: capitalize;',
'  padding: 10px 14px;',
'  border: none;',
'  border-radius: 4px;',
'  cursor: pointer;',
'  background: #348BEF;',
'}',
'',
'.sort-btn {',
'  background-color: #f2f2f2;',
'}',
'',
'.add-btn {',
'  background-color: #007bff;',
'  color: #fff;',
'}',
'',
'.table-wrapper {',
'  overflow-x: auto;',
'}',
'',
'table {',
'  width: 100%;',
'  border-collapse: collapse;',
'  margin-bottom: 20px;',
'  min-width: 800px;',
'}',
'',
'thead {',
'  background-color:#2C2E2F;',
'  color: white;',
'}',
'',
'th{',
'  padding: 12px;',
'  text-align: left;',
'  border-bottom: 1px solid #ddd;',
'  white-space: nowrap;',
'  font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #F6F7F9;',
'}',
'',
'td {',
'  padding: 12px;',
'  text-align: left;',
'  border-bottom: 1px solid #ddd;',
'  white-space: nowrap;',
'  font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #7A7A7A; ',
'}',
'',
'.status {',
'  padding: 4px 10px;',
'  border-radius: 10px;',
'  font-size: 0.9em;',
'  display: inline-block;',
'}',
'',
'.status.active {',
'  background-color: #d4f8d4;',
'  color: #2d7f2d;',
'}',
'',
'.status.inactive {',
'  background-color: #f8d4d4;',
'  color: #a94442;',
'}',
'',
'.pagination {',
'  display: flex;',
'  flex-wrap: wrap;',
'  gap: 10px;',
'  align-items: center;',
'  justify-content: space-between;',
'  padding: 30px 0px;',
'}',
'',
'.pagination select {',
'  padding: 5px;',
'  width: 81;',
'height: 40;',
'left: 91px;',
'opacity: 0.4;',
'border-radius: 6px;',
'font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #0C0C0C;',
'}',
'',
'.pagination span{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'/* color: #0C0C0C; */',
'}',
'',
'.page-buttons {',
'  display: flex;',
'  gap: 5px;',
'  flex-wrap: wrap;',
'}',
'',
'.product-description2{',
'    font-family: Helvetica;',
'font-weight: 400;',
'font-style: Regular;',
'font-size: 14px;',
'leading-trim: NONE;',
'line-height: 150%;',
'letter-spacing: 0%;',
'text-transform: capitalize;',
'color: #7A7A7A;',
'}',
'',
'.page-buttons button {',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'line-height: 16px;',
'letter-spacing: 0%;',
'gap: 8px;',
'width: 40;',
'height: 40;',
'padding-top: 12px;',
'padding-right: 16px;',
'padding-bottom: 12px;',
'padding-left: 16px;',
'border-radius: 4px;',
'background: #E2E2E2;',
'color: #ABB3C5;',
'border:none;',
'}',
'',
'.page-buttons .active-page {',
'  /* background-color: #333;',
'  color: white;',
'  font-weight: bold; */',
' font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'line-height: 16px;',
'letter-spacing: 0%;',
'color: #2D416F;',
'border: none;',
'}',
'',
'@media (max-width: 768px) {',
'  .controls {',
'    flex-direction: column;',
'    align-items: stretch;',
'  }',
'',
'  .sort-btn,',
'  .add-btn {',
'    width: 100%;',
'  }',
'',
'  .pagination {',
'    flex-direction: column;',
'    align-items: flex-start;',
'  }',
'',
'  table {',
'    font-size: 14px;',
'  }',
'}',
'',
'',
'.t-Body .t-Tabs--simple .t-Tabs-link{',
'    border-top: 1px solid #ddd;',
'}',
'',
'',
'.ui-dialog-titlebar{',
'    align-items: center;',
'    text-align: center;',
'} ',
'',
'/** Ratings and Recommendations **/',
'',
'.ratings-card {',
'  /* border-radius: 1.25rem; */',
'  background-color: transparent; /* remove background */',
'  border-radius: 0;              /* remove rounded corners */',
'  box-sizing: border-box;',
'  box-shadow: none;              ',
'  border: none;',
'  padding: 1rem;',
'  margin: 1rem 0;',
'  width: 100%;',
'  max-width: 800px;',
'  /* box-sizing: border-box;',
'  box-shadow: 0 2px 6px rgba(0,0,0,0.05);  */',
'}',
'',
'.description {',
'    font-family: Helvetica;',
'    font-weight: 400;',
'    font-size: 16px;',
'    line-height: 150%;',
'    letter-spacing: 0%;',
'    color: #423B3B;',
'}',
'',
'.author {',
'  display: flex;',
'  align-items: center;',
'  background: #F7F7F7;',
'  border-radius: 30px;',
'}',
'',
'.avatar {',
'  width: 20px;',
'  height: 20px;',
'  border-radius: 50%;',
'  margin-right: 0.5rem;',
'  object-fit: cover;',
'}',
'',
'.name {',
'    font-family: Helvetica;',
'    font-weight: 400;',
'    font-size: 14px;',
'    line-height: 150%;',
'    letter-spacing: 0%;',
'    vertical-align: middle;',
'    text-transform: capitalize;',
'    color: #423B3B;',
'}',
'',
'.review-section {',
'  font-family: Helvetica;',
'  margin: 10px auto; ',
'  padding: 10px;  ',
'',
'}',
'',
'.review-box {',
'  /* background-color: #f9f9f9; */',
'  border-radius: 8px;',
'  /* padding: 15px; */',
'  margin-top: 10px;',
'}',
'',
'.review-title{',
'      display: flex;',
'  justify-content: space-between;',
'  align-items: center;',
'}',
'',
'.review-actions {',
'  display: flex;',
'  gap: 10px;',
'}',
'',
'.action-btn {',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'  border: none;',
'  padding: 5px 10px;',
'  border-radius: 4px;',
'  cursor: pointer;',
'}',
'',
'.action-btn.edit {',
'  background-color: #007bff;',
'  color: white;',
'}',
'',
'.action-btn.delete {',
'  background-color: #dc3545;',
'  color: white;',
'}',
'',
'.action-btn:hover {',
'  opacity: 0.85;',
'}',
'',
'.review-box strong{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 16px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'color: #423B3B;',
'}',
'',
'.review-box p {',
'  margin: 10px 0;',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'color: #423B3B;',
'}',
'',
'.reviewer {',
'  display: flex;',
'  align-items: center;',
'  margin-top: 10px;',
'  background: #F7F7F7;',
'  border-radius: 30px;',
'gap: 6px;',
'padding-top: 4px;',
'padding-right: 8px;',
'padding-bottom: 4px;',
'padding-left: 8px;',
'',
'}',
'',
'.reviewer-photo {',
'  width: 20px;',
'  height: 20px;',
'  border-radius: 50%;',
'  margin-right: 8px;',
'}',
'',
'.reviewer-name {',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 12px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'vertical-align: middle;',
'text-transform: capitalize;',
'color: #423B3B;',
'}',
'',
'.review-button {',
'  float: right;',
'  background-color: #007bff;',
'  color: white;',
'  border: none;',
'  padding: 8px 14px;',
'  border-radius: 5px;',
'  cursor: pointer;',
'  /* margin-top: 15px; */',
'}',
'',
'.review-button:hover {',
'  background-color: #0056b3;',
'}',
'',
'.review-header {',
'  display: flex;',
'  justify-content: space-between;',
'  align-items: center;',
'  text-align: center;',
'  margin-bottom: 15px;',
'}',
'',
'.review-header h3{',
'    font-family: Helvetica;',
'    font-weight: 700;',
'    font-size: 18px;',
'    line-height: 100%;',
'    letter-spacing: 0%;',
'    color: #32373B;',
'    margin: 0;',
'}',
'',
'/* Responsive tweaks */',
'@media (max-width: 600px) {',
'  .description {',
'    font-size: 16px;;',
'  }',
'',
'  .name {',
'    font-size: 14px;',
'  }',
'',
'  .avatar {',
'    width: 1.75rem;',
'    height: 1.75rem;',
'  }',
'}',
'',
'/* Responsive rule */',
'@media (max-width: 600px) {',
'  .review-header {',
'    flex-direction: column;',
'    align-items: flex-start;',
'  }',
'',
'  .review-button {',
'    align-self: flex-start;',
'  }',
'}',
'',
'ul{',
'    font-family: Helvetica;',
'font-weight: 400;',
'font-size: 16px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'text-transform: capitalize;',
'color: #7A7A7A;',
'}',
'',
'.comp-desc{',
'        font-family: Helvetica;',
'font-weight: 400;',
'font-size: 16px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'color: #7A7A7A;',
'}',
'',
'.a-AlertMessage{',
'    padding: 20px;',
'}',
'',
'.a-AlertMessage-icon{',
'    background-color: #D0E4FB;',
'    padding: 10px;',
'}',
'',
'.a-AlertMessage-title{',
'    font-family: Helvetica;',
'}',
'',
'.a-AlertMessage-details{',
'      font-family: Helvetica;',
'}',
'js-confirmBtn ui-button ui-corner-all ui-widget ui-button--hot{',
'    font-family: Helvetica;',
'}',
'',
''))
,p_page_template_options=>'#DEFAULT#'
,p_page_component_map=>'25'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(49600044980429323)
,p_plug_name=>'Marketplace'
,p_icon_css_classes=>'fa-ai-sparkle-generate-list'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(2504366637224064)
,p_plug_display_sequence=>20
,p_location=>null
,p_menu_id=>wwv_flow_imp.id(2462480760224025)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_imp.id(2562100272224107)
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(93644599352203176)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(2487713801224053)
,p_plug_display_sequence=>30
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'',
'BEGIN',
'  -- Fetch the companies from company table.',
' FOR i in (SELECT ',
'              company_id,',
'              company_name,',
'              company_desc,',
'              decode(company_status, ''A'', ''Active'', ''I'', ''Inactive'') status,',
'              img_url',
'             FROM XXMRKT.XXMRKT_COMPANY_LIST',
'             WHERE COMPANY_TYPE = ''Loan Services''',
'             AND COMPANY_cODE = :AP_COMPANY_CODE',
'             AND COMPANY_ID = :P68_COMPANY_ID',
'             ORDER BY 1',
') LOOP',
'  RETURN',
'        ''<div class="top-region-header">',
'                <div>    ',
'                    <button class="icon-button" onclick="return redirectToMainPageFunc(66)">',
'                      <img src="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/svgs/solid/arrow-left.svg" alt="Left Arrow" width="24" height="24" class="icon">',
'                      <span class="button-text">Back</span>',
'                    </button>',
'                </div>',
'                <div class = "internal-flex">',
'                    <div class="img-div">',
'                        <img class ="prod-img" src="https://testapp.softsuite.com/softsuite/api/mrkt/getimages/''||:P68_COMPANY_ID||''" alt="group">',
'                    </div>',
'                    <div class="text-set">',
'                        <p class="company_name">''||i.company_name||''</p>'';',
'                        if i.status = ''Active'' then',
'                            RETURN ''<span style="background:#ECFDF3">''||i.status||''</span>'';',
'                        else',
'                            RETURN ''<span>''||i.status||''</span>'';',
'                        end if;',
'             RETURN ''</div>',
'                </div>',
'          </div>    ',
'         '';',
'    END LOOP;',
'END;'))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(93645514130203185)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#:t-TabsRegion-mod--simple'
,p_plug_template=>wwv_flow_imp.id(2515855534224073)
,p_plug_display_sequence=>50
,p_location=>null
,p_ai_enabled=>false
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(93646417702203194)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#:js-useLocalStorage:t-TabsRegion-mod--fillLabels:t-TabsRegion-mod--simple'
,p_plug_template=>wwv_flow_imp.id(2515855534224073)
,p_plug_display_sequence=>40
,p_location=>null
,p_ai_enabled=>false
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(59568781365157307)
,p_plug_name=>'Loan History'
,p_parent_plug_id=>wwv_flow_imp.id(93646417702203194)
,p_region_template_options=>'#DEFAULT#:t-Region--removeHeader:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(2509084578224068)
,p_plug_display_sequence=>40
,p_plug_display_point=>'SUB_REGIONS'
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_insfees_type varchar2(100);',
'    v_charges_type varchar2(100);',
'BEGIN',
'',
'RETURN ',
'    ''',
'<body>',
'',
'  <div class="controls">',
'    <h2>Loan History</h2>',
'  </div>',
'',
'  <div class="table-wrapper">',
'    <table>',
'      <thead>',
'        <tr>',
'          <th>Loan Name</th>',
'          <th>Loan Type</th>',
'          <th>Interest Rate %</th>',
'          <th>Loan Amount</th>',
'          <th>Duration</th>',
'          <th>Start Date</th>',
'          <th>End Date</th>',
'          <th>Loan Status</th>',
'          <th>Action</th>',
'        </tr>',
'      </thead>',
'      <tbody id="loan-table-body">',
'        <!-- Dynamic rows go here -->',
'      </tbody>',
'    </table>',
'  </div>',
'',
'  <div class="pagination">',
'    <span>Showing</span>',
'    <select id="page-select" class="page-select"></select>',
'    <span>out of <span id="total-pages"></span></span>',
'',
'    <div class="page-buttons">',
'      <!-- Dynamic page buttons -->',
'    </div>',
'  </div>',
'</body>'';',
'END;'))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
,p_plug_display_condition_type=>'NEVER'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(93646493142203195)
,p_plug_name=>'Description'
,p_parent_plug_id=>wwv_flow_imp.id(93646417702203194)
,p_region_template_options=>'#DEFAULT#:t-Region--removeHeader:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(2509084578224068)
,p_plug_display_sequence=>10
,p_plug_display_point=>'SUB_REGIONS'
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'    l_content clob;',
'    q_content clob;',
'    v_data clob;',
'begin',
'',
'    for i in (SELECT ',
'              company_id,',
'              company_name,',
'              company_desc,',
'              decode(company_status, ''A'', ''Active'', ''I'', ''Inactive'') status,',
'              img_url,',
'              benefits',
'             FROM XXMRKT.XXMRKT_COMPANY_LIST',
'             WHERE COMPANY_ID = :P68_COMPANY_ID',
'              and company_code = :AP_cOMPANY_cODE)',
'    loop',
'    ',
'        RETURN ''<div class = "container">',
'                    <div class="product-description">',
'                        <p class="description-header">Description</p>',
'                        <p class="comp-desc">''||i.company_Desc||''</p>',
'                    </div>',
'                    <div class="product-description2">',
'                              <p class="description-header">Key Features</p>',
'                            ''||i.benefits||''',
'                    </div>',
'                </div>'';',
'     end loop;',
'    ',
'end;'))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(93646614637203196)
,p_plug_name=>'Product'
,p_parent_plug_id=>wwv_flow_imp.id(93646417702203194)
,p_region_template_options=>'#DEFAULT#:t-Region--removeHeader:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(2509084578224068)
,p_plug_display_sequence=>30
,p_plug_display_point=>'SUB_REGIONS'
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_comp_type    VARCHAR2(100);',
'    v_type         NUMBER; -- 1 is for loan services',
'    v_count        NUMBER;',
'    v_offset       NUMBER;',
'    v_page_size    NUMBER := 5;',
'    v_process      VARCHAR2(200) := ''''''GET_DATA'''''';',
'    v_item         VARCHAR2(100) := ''''''P68_PROD_OFFSET'''''';',
'    v_region         VARCHAR2(100) := ''''''products'''''';',
'    v_last_Shown NUMBER := 0;',
'BEGIN',
'',
'    BEGIN',
'        v_offset := TO_NUMBER(:P68_PROD_OFFSET);',
'    EXCEPTION',
'        WHEN VALUE_ERROR THEN',
'            v_offset := 1;',
'    END;',
'    -- Get company type',
'    BEGIN',
'        SELECT COMPANY_TYPE',
'          INTO v_comp_type',
'          FROM XXMRKT.XXMRKT_COMPANY_LIST',
'         WHERE COMPANY_ID = :p68_company_id;',
'    EXCEPTION',
'        WHEN NO_DATA_FOUND THEN',
'            NULL;',
'    END;',
'',
'    -- Count users for pagination',
'    SELECT CEIL(COUNT(*) / v_page_size)',
'      INTO v_count',
'    FROM XXMRKT.XXMRKT_PRODUCT_LIST A, ',
'      --  XXHRMS.XXHRMS_ELEMENTS B, ',
'        XXMRKT.XXMRKT_LOAN_TYPES C,',
'        XXMRKT.XXMRKT_COMPANY_LIST D',
'    WHERE A.COMPANY_ID = :p68_company_id',
'    AND A.COMPANY_CODE = :AP_COMPANY_CODE',
'  --  AND A.DEDUCTION_HEADER = B.ELEMENT_ID',
'    AND A.COMPANY_ID = D.COMPANY_ID',
'    AND to_Char(A.PRODUCT_TYPE) = to_char(C.LOAN_TYPE_ID)',
'    AND D.COMPANY_TYPE = ''Loan Services''',
'    ORDER BY A.CREATION_DATE DESC;',
'',
'    -- Render HTML if company type is Loan Services',
'    IF v_comp_type = ''Loan Services'' THEN',
'        v_type := 1;',
'',
'        IF v_offset < 1 THEN',
'            v_offset := 1;',
'        ELSIF v_offset > v_count THEN',
'            v_offset := v_count;',
'        END IF;',
'                        -- Begin HTML Output',
'        htp.p(''',
'              <div class="controls">',
'				<h2>Products</h2>',
'				<div>',
'				<input type="text" id="product-search" placeholder="Search products..." onkeyup="filterProducts()" class="search-input">',
'				</div>',
'			  </div>',
'',
'			  <div class="table-wrapper">',
'				<table>',
'				  <thead>',
'					<tr>',
'					  <th>Product Name</th>',
'					  <th>Product Type</th>',
'					  <th>Interest Rate %</th>',
'					  <th>Charges</th>',
'					  <th>Insurance Fees</th>',
'					  <th>Action</th>',
'					</tr>',
'				  </thead>',
'				  <tbody id="product-table-body">',
'					<!-- Dynamic rows go here -->',
'				  </tbody>',
'				</table>',
'			  </div>'');',
'                    -- Pagination Controls',
'                    htp.p(''<div class="pagination">',
'              <div class="showing">',
'                <span>Showing</span>',
'                <select id="products-select" onchange="handlePageChange(this,''|| v_process || '', '' || v_item || '', ''||v_region||'','' || v_count || '')">'');',
'',
'                    FOR i IN 1..v_count LOOP',
'                        IF i = v_offset THEN',
'                            htp.p(''<option value="'' || i || ''" selected>'' || i || ''</option>'');',
'                        ELSE',
'                            htp.p(''<option value="'' || i || ''">'' || i || ''</option>'');',
'                        END IF;',
'                    END LOOP;',
'',
'                    htp.p(''</select>',
'                        <span>out of <span id="total-pages">'' || v_count || ''</span></span>',
'                      </div>',
'',
'                      <div class="page-buttons">',
'                        <button id="prev" onclick="return apprPaginate(-1,'' || v_process || '', '' || v_item || '', '' || v_region || '','' || v_count || '')">&lt;</button>'');',
'',
'                            FOR i IN 1..v_count LOOP',
'                                            -- Show first, last, current, and one before/after current',
'                                IF i = 1 OR i = v_count OR i = v_offset OR i = v_offset - 1 OR i = v_offset + 1 THEN',
'                                  ',
'                                  -- If there is a gap between last shown and current, add ellipsis',
'                                  IF v_last_shown <> 0 AND i > v_last_shown + 1 THEN',
'                                    htp.p(''<span class="pagination-ellipsis">...</span>'');',
'                                  END IF;',
'',
'                                  -- Render button',
'                                  htp.p(''<button onclick="return getData('' || i || '', '' || v_process || '', '' || v_region || '')">'' || i || ''</button>'');',
'                                  v_last_shown := i;',
'',
'                                END IF;',
'                            END LOOP;',
'',
'                            htp.p(''<button onclick="return apprPaginate(1, '' || v_process || '', '' || v_item || '', '' || v_region || '','' || v_count || '')">&gt;</button>',
'                    </div>'');',
'',
'                    -- Close Wrapper',
'                    htp.p(''</div>',
'            '');',
'',
'        RETURN NULL;',
'    END IF;',
'EXCEPTION',
'    WHEN OTHERS THEN ',
'         null;',
'END;',
''))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(93646729246203198)
,p_plug_name=>'Ratings and Recommendations'
,p_region_name=>'rating'
,p_parent_plug_id=>wwv_flow_imp.id(93646417702203194)
,p_region_template_options=>'#DEFAULT#:t-Region--removeHeader:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(2509084578224068)
,p_plug_display_sequence=>50
,p_plug_display_point=>'SUB_REGIONS'
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'',
'BEGIN',
'htp.p(''<div class="review-section id="rating">',
'            <div class="review-header">',
'            <h3>Reviews/Recommendations</h3>',
'            <button class="review-button" onclick="return redirectToModalPage69WriteAReview(69,''||:P68_COMPANY_ID||'')">Share a Review</button>',
'          </div>'');',
'        FOR i IN (select review_id,',
'                         decode(rating, 5, ''Excellent'', 4, ''Very Good'', 3, ''Average'', 2, ''Poor'', 1, ''Bad/ Avoid Product'', 0, ''Not Rated'') rating,',
'                         comments,',
'                         reviewer_name,',
'                         reviewer_id',
'                    from XXMRKT.XXMRKT_PRODUCT_REVIEWS',
'                    where COMPANY_ID = :P68_COMPANY_ID',
'                    and COMPANY_CODE = :AP_COMPANY_CODE',
'                    and reviewer_id = :AP_STAFF_ID',
'                  ) ',
'        LOOP',
'        htp.p( ',
'        ''',
'          <div class="review-box">',
'             <div class="review-title">',
'                <strong>Product Rating - ''||i.rating||''</strong>',
'                <div class="review-actions">',
'                  <button onclick="return redirectToModalPage69UpdateReview(69,''||:P68_COMPANY_ID||'', ''||i.review_id||'')" class="action-btn edit">Edit Review</button>',
'                  <button onclick="return deleteReview(''||i.review_id||'')" class="action-btn delete">Delete Review</button>',
'                </div>',
'            </div>',
'            <p>',
'              ''||i.comments||''',
'            </p>',
'            ',
'            <div class="reviewer">',
'              <img src="https://testapp.softsuite.com/softsuite/api/mrkt/getreviewerimage/''||i.reviewer_id||''" alt="Reviewer Photo" class="reviewer-photo">',
'              <span class="reviewer-name">''||i.reviewer_name||''</span>',
'            </div>',
'          </div>''',
'        );',
'    END LOOP;',
' htp.p(''</div>',
'',
''');',
'END;'))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(75567453901060743)
,p_name=>'P68_PROD_OFFSET'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_imp.id(93645514130203185)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(82401093094505222)
,p_name=>'P68_PRODUCT_TYPE'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_imp.id(93645514130203185)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(93649309204203232)
,p_name=>'P68_COMPANY_ID'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(93645514130203185)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(49644019689190419)
,p_name=>'New'
,p_event_sequence=>10
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'ready'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(49644440494190424)
,p_event_id=>wwv_flow_imp.id(49644019689190419)
,p_event_result=>'TRUE'
,p_action_sequence=>20
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'apex.util.getTopApex().jQuery(".modal-dialog--pullout .ui-dialog-title").prepend(''<img src="#APP_IMAGES#Featured icon.png" style="height:48px;"/>'');'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(49643609733190418)
,p_process_sequence=>10
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'PROCESS_DATA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'begin',
'   DELETE XXMRKT.XXMRKT_PRODUCT_REVIEWS',
'   WHERE REVIEW_ID = APEX_APPLICATION.g_x01',
'   AND COMPANY_CODE = V(''AP_COMPANY_CODE'');',
'   ',
'   HTP.P(1);',
'',
'exception when others then ',
'HTP.P(0);',
'end;',
'',
'',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>49643609733190418
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(53772057717844401)
,p_process_sequence=>20
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GET_DATA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE ',
'     v_page_size NUMBER := 5;',
'BEGIN',
'      :P68_PROD_OFFSET := apex_application.g_x02;',
'  -- Open JSON array',
'  apex_json.open_array;',
'',
'  FOR pro_rec IN (',
'     SELECT product_id,',
'           company_id,',
'           product_name,',
'           c.loan_type product_type,',
'           interest_rate,',
'           b.name deduction_header,',
'           to_char(nvl(minimum_limit,0), ''999G999G999G999G990D00'') minimum_limit,',
'           to_char(nvl(maximum_limit, 0), ''999G999G999G999G990D00'') maximum_limit,',
'           minimum_repayment_period,',
'           maximum_repayment_period,',
unistr('           decode(charges_type, ''Percentage'', ''%'', ''Amount'', ''\20A6'') charges_type,'),
'           nvl(charges, 0) charges,',
unistr('           decode(insfees_type, ''Percentage'', ''%'', ''Amount'', ''\20A6'') insfees_type,'),
'           nvl(insurance_fee, 0) insurance_fee,',
'           decode(A.status, ''A'', ''Active'', ''I'', ''Inactive'') status',
'    FROM XXMRKT.XXMRKT_PRODUCT_LIST A, XXHRMS.XXHRMS_ELEMENTS B, XXMRKT.XXMRKT_LOAN_TYPES C',
'    WHERE COMPANY_ID = APEX_APPLICATION.g_x01',
'    AND A.COMPANY_CODE = :AP_COMPANY_CODE',
'    AND A.DEDUCTION_HEADER = B.ELEMENT_ID',
'    AND A.PRODUCT_TYPE = C.LOAN_TYPE_ID',
'    AND A.DEDUCTION_HEADER IS NOT NULL',
'    AND A.STATUS = ''A''',
'    AND EXISTS (',
'        SELECT 1',
'        FROM XXMRKT.XXMRKT_APPROVAL_SETUP s',
'        WHERE s.company_id = APEX_APPLICATION.g_x01',
'          AND s.company_code = :AP_company_code',
'          AND s.approval_level in (1, 5)',
'          AND S.status = ''A''',
'    )',
'    ORDER BY A.CREATION_DATE DESC',
'  )',
'  LOOP',
'    apex_json.open_object;',
'    apex_json.write(''productID'', pro_rec.product_id);',
'    apex_json.write(''companyID'', pro_rec.company_id);',
'    apex_json.write(''productName'', pro_rec.product_name);',
'    apex_json.write(''productType'', pro_rec.product_type);',
'    apex_json.write(''interestRate'', pro_rec.interest_rate);',
'    apex_json.write(''minimumLimits'', pro_rec.minimum_limit);',
'    apex_json.write(''maximumLimits'', pro_rec.maximum_limit);',
'    apex_json.write(''minimumRepaymentPeriod'', pro_rec.minimum_repayment_period);',
'    apex_json.write(''maximumRepaymentPeriod'', pro_rec.maximum_repayment_period);',
'    apex_json.write(''deductionHeader'', pro_rec.deduction_header);',
'    apex_json.write(''chargesType'', pro_rec.charges_type);',
'    apex_json.write(''charges'', pro_rec.charges);',
'    apex_json.write(''insuranceFeesType'', pro_rec.insfees_type);',
'    apex_json.write(''insuranceFees'', pro_rec.insurance_fee);',
'    apex_json.write(''status'', pro_rec.status);',
'    apex_json.close_object;',
'  END LOOP;',
'',
'  apex_json.close_array;',
'',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    -- Clear previous output (if any)',
'    apex_json.free_output;',
'    ',
'    -- Start fresh JSON error response',
'    apex_json.open_object;',
'    apex_json.write(''status'', ''error'');',
'    apex_json.write(''message'', SQLERRM);',
'    apex_json.close_object;',
'',
'    -- RAISE_APPLICATION_ERROR is optional here; use it to signal error to JavaScript',
'    -- raise_application_error(-20001, SQLERRM);',
'END;',
'',
'',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>53772057717844401
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(59569634134157316)
,p_process_sequence=>30
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GET_LOAN_HIST_DATA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'BEGIN',
'  -- Open JSON array',
'  apex_json.open_array;',
'',
'  FOR pro_rec IN (',
'    SELECT B.PRODUCT_NAME,',
'       C.LOAN_TYPE,',
'       B.INTEREST_RATE,',
'       A.LOAN_aMOUNT,',
'       A.DURATION,',
'       A.START_DATE,',
'       A.END_dATE,',
'       A.LOAN_STATUS',
'    FROM XXMRKT.XXMRKT_APPLIED_LOANS A, XXMRKT.XXMRKT_PRODUCT_LIST B, XXMRKT.XXMRKT_LOAN_TYPES C',
'    WHERE A.COMPANY_ID = 4--APEX_APPLICATION.g_x01',
'    AND A.COMPANY_CODE = :AP_COMPANY_CODE',
'    AND A.PRODUCT_ID = B.PRODUCT_ID',
'    AND A.CREATED_BY = :AP_STAFF_ID',
'    AND B.PRODUCT_TYPE = C.LOAN_TYPE_ID',
'    ORDER BY A.CREATION_DATE DESC',
'  )',
'  LOOP',
'    apex_json.open_object;',
'    apex_json.write(''loanName'', pro_rec.product_name);',
'    apex_json.write(''loanType'', pro_rec.loan_type);',
'    apex_json.write(''interestRate'', pro_rec.interest_rate);',
'    apex_json.write(''loanAmount'', pro_rec.loan_amount);',
'    apex_json.write(''loanDuration'', pro_rec.duration);',
'    apex_json.write(''startDate'', pro_rec.start_date);',
'    apex_json.write(''endDate'', pro_rec.end_date);',
'    apex_json.write(''loanStatus'', pro_rec.loan_status);',
'    apex_json.close_object;',
'  END LOOP;',
'',
'  apex_json.close_array;',
'',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    -- Clear previous output (if any)',
'    apex_json.free_output;',
'    ',
'    -- Start fresh JSON error response',
'    apex_json.open_object;',
'    apex_json.write(''status'', ''error'');',
'    apex_json.write(''message'', SQLERRM);',
'    apex_json.close_object;',
'',
'    -- RAISE_APPLICATION_ERROR is optional here; use it to signal error to JavaScript',
'    -- raise_application_error(-20001, SQLERRM);',
'END;',
'',
'',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>59569634134157316
);
wwv_flow_imp.component_end;
end;
/
