prompt --application/pages/page_00067
begin
--   Manifest
--     PAGE: 00067
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>3780766536418114
,p_default_application_id=>2000004
,p_default_id_offset=>0
,p_default_owner=>'XXSBS'
);
wwv_flow_imp_page.create_page(
 p_id=>67
,p_name=>'Product Description'
,p_alias=>'J266'
,p_page_mode=>'MODAL'
,p_step_title=>'Product Description'
,p_autocomplete_on_off=>'OFF'
,p_javascript_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'var modal = document.getElementById(''main-modal'');',
'',
'function afterLoad(){',
'    apex.message.showPageSuccess(''success'');',
'}',
'',
'function fetchImg(){',
'      apex.server.process("GET_IMAGE", {',
'        x01: $v(''AP_STAFF_ID'')',
'      }, {',
'',
'        dataType: ''text'',',
'        success: function(pData) {',
'           console.log(pData);',
'        }',
'      });',
'   /* const imgElement = document.getElementById(''image'');',
'    const objectURL = URL.createObjectURL(mBlob);',
'    imgElement.src = objectURL; */',
'}',
'',
'/*window.onload = function() {',
'            fetchImg();  // Call the function',
'        };*/',
'',
'function testRedirect(){',
'       var x = ''Y'';',
'        var url = "f?p=#APP_ID#:"+''1''+":#SESSION#::NO:RP";',
'        url = url.replace("#APP_ID#",&APP_ID.);',
'',
'        url = url.replace("#SESSION#", &SESSION.);',
'',
'        url = url.replace("#PARA1#", x);',
'',
'        apex.server.process("PREPARE_URL", {',
'',
'                    x01: url',
'',
'        }, {',
'',
'        success: function(pData) {',
'',
'        if (pData.success === true) {',
'             //   apex.navigation.redirect(pData.url);',
'          //  console.log(url);',
'            apex.navigation.dialog.close( true);',
'',
'        } else {',
'',
'                console.log("FALSE");',
'',
'        }',
'',
'        },',
'',
'        error: function(request, status, error) {',
'',
unistr('               console.log("status\2014" + status + " error\2014-" + error);'),
'',
'        }',
'',
'    });',
'    ',
'    ',
'            return false;',
'}',
'',
'function open_dialog(){',
' $(''#confirm-action'').dialog(''open''); //calling region id here to open',
'    return false;',
'}',
'',
'function openDeactivateDialog(){',
' $(''#deactivate-action'').dialog(''open''); //calling region id here to open',
'    return false;',
'}',
'',
'function closeMainModal(){',
'    $(''#modalwindow'').modal(''hide'');',
'    //  javascript:apex.navigation.dialog.close(true);',
'    return false;',
'}',
'',
'function closeModal(){',
'    apex.navigation.dialog.close(true);',
'    return false;',
'}',
'function closeInlineModal(){',
'     $(''#confirm-action'').dialog(''close''); ',
'     $(''#deactivate-action'').dialog(''close''); ',
'    return false;',
'}',
'',
'',
'function completeAction(action, id){',
'    let product_id = $v(''P30_PRODUCT_ID'');',
'    if(action == 1){ // 1 means activate',
'      apex.server.process("COMPLETE_ACTION", {',
'        x01:  ''A'',',
'        x02:  product_id,',
'      }, {',
'',
'        dataType: ''text'',',
'        success: function(pData) {',
'            if(pData == 1){ // 1 means successful',
'                redirectFunc(''activate'', ''S''); // activate and successful',
'            }else{ ',
'                redirectFunc(''activate'', ''F''); //activate and failed',
'            }',
'        }',
'      });',
'    }else{',
'        apex.server.process("COMPLETE_ACTION", {',
'            x01:  ''I'',',
'            x02:  product_id,',
'          }, {',
'',
'            dataType: ''text'',',
'            success: function(pData) {',
'                if(pData == 1){ // 1 means successful',
'                   redirectFunc(''deactivate'', ''S''); // activate and successful',
'                }else{ ',
'                   redirectFunc(''deactivate'', ''F''); //activate and failed',
'                }',
'            }',
'          });',
'    }',
'    return false;',
'}',
'',
'',
'// Get the tabs by their IDs',
'const descTab = document.getElementById(''descTab'');',
'const ratingsTab = document.getElementById(''ratingsTab'');',
'',
'// Function to switch the active tab',
'function switchTab(event) {',
'    // Remove the ''active'' class from both tabs',
'    descTab.classList.remove(''active'');',
'    ratingsTab.classList.remove(''active'');',
'    descTabContent.classList.remove(''active'');',
'    ratingsTabContent.classList.remove(''active'');',
'    ',
'    // Add the ''active'' class to the clicked tab',
'    event.target.classList.add(''active'');',
'    ',
'     // Show the corresponding content by adding the ''active'' class',
'    if (event.target === descTab) {',
'        descTabContent.classList.add(''active'');',
'    } else if (event.target === ratingsTab) {',
'        //null;',
'        ratingsTabContent.classList.add(''active'');',
'    }',
'}',
'',
'// Add event listeners to the tabs to handle the click event',
'descTab.addEventListener(''click'', switchTab);',
'ratingsTab.addEventListener(''click'', switchTab);',
'',
'',
'const redirectFunc = (product_id) => {',
'        var x = product_id;',
'        var url = "f?p=#APP_ID#:"+''66''+":#SESSION#::NO:RP,66:P66_PRODUCT_ID:#PARA1#";',
'        url = url.replace("#APP_ID#",&APP_ID.);',
'',
'        url = url.replace("#SESSION#", &SESSION.);',
'',
'        url = url.replace("#PARA1#", x);',
'',
'        apex.server.process("PREPARE_URL", {',
'',
'                    x01: url',
'',
'        }, {',
'',
'        success: function(pData) {',
'',
'        if (pData.success === true) {',
'',
'                apex.navigation.redirect(pData.url);',
'',
'        } else {',
'',
'                console.log("FALSE");',
'',
'        }',
'',
'        },',
'',
'        error: function(request, status, error) {',
'',
unistr('               console.log("status\2014" + status + " error\2014-" + error);'),
'',
'        }',
'',
'    });',
'    ',
'    ',
'            return false;',
'        ',
'};',
'',
'function closeSubmitDialog(){',
' let product_id = $v(''P67_PRODUCT_ID'');',
' apex.server.process(',
'        "GET_REDIRECT_URL", // The name of the APEX process to be called',
'        {  ',
'            x01: product_id',
'        },',
'        {',
'            async: true, // Asynchronous request',
'            dataType: "text", // Expecting text as the return type',
'            success: function(pdata) {',
'                if(pdata == 1) {',
'                     apex.navigation.dialog.close(true);',
'                   //  location.reload();',
'                     //setItem(''P26_PRODUCT_ID'', '' '');',
'                }else{',
'                      $s(''P67_ACTION'', pdata);',
'                     apex.navigation.dialog.close(true, ["P67_PRODUCT_ID", "P67_ACTION"] );',
'                    // window.location.href = pdata;',
'                };',
'            },',
'            error: function(jqXHR, textStatus, errorThrown) {',
'                console.error("Error setting session state: " + textStatus + " - " + errorThrown);',
'            }',
'        }',
'    );  ',
'',
'    return false;',
'}',
''))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'.now-p .text {',
'  font-size: 13px;',
'  padding-left: 40px;',
'}',
'',
'.now-p{',
'   font:Helvetica;',
'   color: #423B3B;',
'}',
'',
'.now-bold-text{',
'    font-family: Helvetica;',
'    font-size: 16px;',
'    font-weight: 700;',
'    line-height: 30px;',
'    text-align: left;',
'    color:#423B3B;',
'}',
'',
'.modal-header{',
'  display: flex;',
'  flex-wrap: wrap;',
'  align-items:center;',
'  justify-content:space-between;',
'    background-color: #FFFFFF;',
'    padding: 15px;',
'    text-align: center;',
'    position: fixed;',
'    top: 0;',
'    left: 0;',
'    width: 100%;',
'   /* height: 75px;*/',
'    z-index: 10;',
'    /*top: 0;',
'    position:fixed;',
'    width: 100%;*/',
'}',
'',
'.modal-header img{',
'   margin: 5px 0px;',
'   padding: 0px 9px;',
'   width:86%;',
'   height:auto;',
'   object-fit:cover;',
'   object-position:50% 50%;',
'}',
'',
'.modal-body-main{',
'    padding-top: 50px;  ',
'    padding-bottom: 60px; ',
'    margin: 0 auto;',
'    height: calc(100vh -100px);  ',
'    overflow-y: auto;  ',
'    /*overflow: hidden;*/  ',
'    ',
'}',
'',
'.modal-body1{',
'    margin-bottom: 20px;',
'    margin-top: 12px;',
'}',
'',
'.modal-product-title{',
'    display: flex;',
'  flex-wrap: wrap;',
'  align-items:center;',
'  justify-content:space-between;',
'}',
'',
'',
'.modal-product-title span{',
'      background-color:#F2F4F7;',
'    width: Hug (62px)px;',
'    height: Hug (22px)px;',
'    padding: 2px 8px;',
'    gap: 0px;',
'    border-radius: 16px;',
'    opacity: 0px;',
'    font-size: 12px;',
'    font-weight: 500;',
'    text-align: center;',
'    color:#344054;',
'    font-weight: 500;',
'    line-height: 18px;',
'}',
'',
'.company-description{',
'    margin-top: 12px;',
'}',
'',
'.company-description p{',
'    font-size: 14px;',
'}',
'.product-description{',
'    margin: 12px 0px;',
'    border-top: 1px solid #EAEAEA;',
'}',
'',
'.product-description2{',
'    margin: 12px 0px;',
'    border-top: 1px solid #EAEAEA;',
'}',
'',
'.activate-btn{',
'    margin-top: 12px;',
'}',
'',
'.activate-button{',
'    display: block;',
'    width: 100%;',
'    padding: 15px 0px;',
'    margin-top: 12px;',
'    border-radius: 4px;',
'    cursor: pointer;',
'    background: #348BEF;',
'    border:none;',
'    font-family: Helvetica;',
'    font-size: 14px;',
'    font-weight: 700;',
'    line-height: 16.1px;',
'    letter-spacing: -0.01em;',
'    color: #FFFFFF;',
'}',
'',
'.deactivate-button{',
'    display: block;',
'    width: 100%;',
'    padding: 15px 0px;',
'    margin-top: 12px;',
'    border-radius: 4px;',
'    cursor: pointer;',
'    background: #348BEF;',
'    border:none;',
'    font-family: Helvetica;',
'    font-size: 14px;',
'    font-weight: 700;',
'    line-height: 16.1px;',
'    letter-spacing: -0.01em;',
'    color: #FFFFFF;',
'}',
'',
'.description-header{',
'    font-family: Helvetica;',
'    font-size: 16px;',
'    font-weight: 700;',
'    line-height: 24px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none; ',
'    width: Fill (531px)px;',
'    height: Fixed (48px)px;',
'    padding: 8px 0px 0px 0px;',
'    gap: 8px;',
'    border-radius: 4px 0px 0px 0px;',
'    opacity: 0px;',
'    color: #423B3B;',
'}',
'',
'',
'.myButtons{',
'    background:#FFFFFF;',
'    color: white;',
'    padding: 0px 15px;',
'    padding-bottom: 15px;',
'    text-align: center;',
'    position: fixed;',
'    bottom: 0;',
'    left: 0;',
'    width: 100%;',
'    z-index: 10;',
'}',
'/*Inline Dialog*/',
'.ui-dialog-titlebar{',
'    display:none;',
'}',
'',
'.ui-dialog{',
'     width: 80%!important;',
'    height:43%!important;',
'    top: 25%!important;',
'    border-radius: 12px!important;',
'}',
'',
'.t-DialogRegion-body{',
'    padding: 10px 0px;',
'}',
'',
'',
'.inline-modal-header{',
'     display: flex;',
'  flex-wrap: wrap;',
'  align-items:center;',
'  justify-content:space-between;',
'}',
'',
'.inline-modal-header img{',
'   width:65%;',
'   height:auto;',
'   object-fit:cover;',
'   object-position:50% 50%;',
'}',
'',
'.light-p{',
'    styleName: Text sm/Regular;',
'    font-family: Helvetica;',
'    font-size: 14px;',
'    font-weight: 400;',
'    line-height: 20px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'    color: #667085;',
'}',
'',
'.dark-p{',
'    font-family: Helvetica;',
'    font-size: 14px;',
'    font-weight: 700;',
'    line-height: 28px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'    color: #101828;',
'}',
'',
'/*Inline dialog buttons*/',
'.inline-submit{',
'    display: flex;',
'  flex-wrap: wrap;',
'  align-items:center;',
'  justify-content:space-between;',
'  margin-top: 30px;',
'}',
'',
'.cancel-button{',
'    width: Fixed (210px)px;',
'    height: Fixed (48px)px;',
'    padding: 8px 40px;',
'    gap: 0px;',
'    border-radius: 4px;',
'    border: 1px solid #7D7D7D;',
'    font-family: Helvetica;',
'    font-size: 14px;',
'    font-weight: 700;',
'    line-height: 16.1px;',
'    letter-spacing: -0.01em;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'    color: #7D7D7D;',
'}',
'',
'.submit-button{',
'    width: 100%;',
'    height: Fixed (48px)px;',
'    padding: 8px 40px;',
'    gap: 0px;',
'    border-radius: 4px;',
'    border: none;',
'    background: #348BEF;',
'    color:#FFFFFF;',
'    font-family: Helvetica;',
'    font-size: 14px;',
'    font-weight: 700;',
'    line-height: 16.1px;',
'    letter-spacing: -0.01em;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'}',
'',
'.m-top{',
'    display: flex;',
'  align-items: center;',
'  justify-content: left;',
'  margin-bottom :12px ;',
'}',
'',
'.m-top-img{',
'    margin-right: 10px;',
'    padding: 4px;',
'}',
'.m-top-img img{',
'width: Fixed (48px)px;',
'height: Fixed (48px)px;',
'gap: 10px;',
'border: 1px solid #DDDDDD;',
'border-radius: 4px;',
'opacity: 0px;',
'}',
'',
'.m-top-text p{',
'    font-family: Helvetica;',
'font-size: 20px;',
'font-weight: 700;',
'line-height: 30px;',
'text-align: left;',
'text-underline-position: from-font;',
'text-decoration-skip-ink: none;',
'color: #423B3B;',
'}',
'',
'.m-bottom-text p {',
'    font-family: Helvetica;',
'font-size: 16px;',
'font-weight: 400;',
'line-height: 24px;',
'text-align: left;',
'text-underline-position: from-font;',
'text-decoration-skip-ink: none;',
'color: #7A7A7A;',
'}',
'',
'.navbar-container {',
'    width: 100%;',
'    max-width: 100%; /* Ensures the navbar container spans the full width */',
'    margin: 12px 0;',
'    border-bottom: 1px solid #EAEAEA;',
'}',
'',
'.navbar {',
'    display: flex;',
'    justify-content: space-around;',
'    padding: 10px 0;',
'    width: 100%;',
'}',
'',
'.navbar ul {',
'    list-style: none;',
'    display: flex;',
'    padding: 0;',
'    margin: 0;',
'    width: 100%;',
'    justify-content: space-around;',
'}',
'',
'.navbar li {',
'    flex: 1;',
'    text-align: center;',
'}',
'',
'.navbar a {',
'    text-decoration: none;',
'    color: #7A7A7A;',
'    font-family: Helvetica;',
'    font-size: 16px;',
'    font-weight: 400;',
'    line-height: 18.4px;',
'    text-align: center;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'    padding: 5px;',
'    display: block;',
'}',
'',
'.navbar a.active {',
'    color: #2A73C7;',
'    border-bottom: 2px solid #2A73C7;',
'    font-family: Helvetica;',
'    font-size: 16px;',
'    padding-bottom: 12px;',
'    font-weight: 500;',
'    line-height: 18.4px;',
'    text-align: center;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'}',
'',
'.navbar a:hover {',
'    text-decoration: none;',
'}',
'',
'/* Styling for the content sections */',
'.m-content {',
'    display: none;',
'}',
'',
'.m-content.active {',
'    display: block;',
'}',
'',
'.m-content-desc-head{',
'    font-family: Helvetica;',
'    font-size: 16px;',
'    font-weight: 700;',
'    line-height: 24px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'    color: #423B3B;',
'}',
'',
'.m-content-desc-text{',
'    font-family: Helvetica;',
'    font-size: 16px;',
'    font-weight: 400;',
'    line-height: 24px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'    color: #7A7A7A;',
'}',
'',
'.m-content-key-features{',
'    margin-top: 12px;',
'    padding-top: 12px;',
'    border-top:1px solid #EAEAEA;',
'}',
'',
'.m-content-key-features li{',
'    font-family: Helvetica;',
'font-size: 16px;',
'font-weight: 400;',
'line-height: 24px;',
'text-align: left;',
'text-underline-position: from-font;',
'text-decoration-skip-ink: none;',
'color: #7A7A7A;',
'}',
'',
'.m-ratings-text{',
'    font-family: Helvetica;',
'    font-size: 16px;',
'    font-weight: 400;',
'    line-height: 24px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'    color: #423B3B;',
'}',
'',
'.m-ratings-desc{',
'display:flex;',
'justify-content: left;',
'align-items: center;',
'padding: 4px 8px 4px 8px;',
'border-radius: 30px;',
'background: #F7F7F7;',
'}',
'',
'.m-rating-img{',
'    margin-right:10px;',
'    border-radius: 50%;',
'}',
'',
'.ratingsTabContent{',
'    padding-bottom: 12px;',
'    border-bottom: 1px solid #EAEAEA;',
'}',
'',
'.m-rating-desc-text p{',
'    font-family: Helvetica;',
'    font-size: 14px;',
'    font-weight: 400;',
'    line-height: 21px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'    color: #423B3B;',
'}'))
,p_page_template_options=>'#DEFAULT#'
,p_dialog_height=>'535'
,p_dialog_width=>'500'
,p_dialog_max_width=>'500'
,p_dialog_css_classes=>'modal-dialog--pullout'
,p_page_component_map=>'10'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(199955647615657763)
,p_plug_name=>'&nbsp'
,p_region_name=>'main-modal'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(2487513223224052)
,p_plug_display_sequence=>30
,p_include_in_reg_disp_sel_yn=>'Y'
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'    l_content clob;',
'    q_content clob;',
'    v_data clob;',
'begin',
'    for i in (select ',
'              product_id,',
'              product_name,',
'              img_url,',
'              product_description,',
'              company_desc,',
'              new_price,',
'              old_price,',
'              decode(product_status, ''A'', ''Active'', ''I'', ''Inactive'') status',
'              from XXSBS_MRKT_PRODUCTS_LISTS',
'              where product_id = :P67_PRODUCT_ID',
'              and company_code = :AP_cOMPANY_cODE)',
'    loop',
'    ',
'        htp.p(''<div class = "container">',
'                    <div class="modal-header">',
'                        <div class="header-img">',
'                            <img src="#APP_IMAGES#Featured icon.png" />',
'                        </div>',
'                        <div class="modal-close">',
'                            <a href="" onclick="return testRedirect()"><img src="#APP_IMAGES#Frame 1769.png" /></a>',
'                        </div>',
'                    </div>',
'                    <div class= "modal-body-main content" id="very-important-read">',
'                        <div class="modal-body1">',
'                            <div class="m-top">',
'                                <div class="m-top-img">',
'                                    <img alt="Image" src="''||i.img_url||''" class="m-img" style="width: 48px; height: 48px; object:cover;">',
'                                </div>',
'                                <div class="m-top-text">',
'                                    <p class="now-bold-text">''||i.product_name||''</p>',
'                                </div>',
'                            </div>',
'                            <div class="m-bottom-text"> ',
'                                   <p class="now-bold-text">''||i.company_desc||''</p>',
'                            </div>',
'                         </div>',
'                         <div class="navbar-container">',
'                            <nav class="navbar">',
'                                <ul>',
'                                    <li><a href="#" class="active" id="descTab">Description</a></li>',
'                                    <li><a href="#" id="ratingsTab">Ratings & Recommendations</a></li>',
'                                </ul>',
'                            </nav>',
'                         </div>',
'                        <!-- Content Divs -->',
'                        <div id="descTabContent" class="m-content active">',
'                            <div class= "m-content-mid">',
'                                <p class="m-content-desc-head">Description</p>',
'                                <p class="m-content-desc-text">''||i.product_description||''</p>',
'                            </div>',
'                            <div class="m-content-key-features">',
'                                <p class="m-content-desc-head">Key Feautures</p>',
'                                    <ul>'');',
'                               for q in ( select *',
'                                          from XXSBS_MRKT_PRODUCTS_LISTS_DET',
'                                          where product_id = i.product_id',
'                                          and company_code = :AP_cOMPANY_cODE)',
'                                            loop',
'                                             htp.p(''',
'                                                  <li>''||q.features||''</li>       ',
'                                             '');',
'                                           end loop;',
'                          htp.p(''</ul> ',
'                            </div>',
'                        </div>'');',
'                   for q in (select a.rating,',
'                                    c.id,',
'                                    b.full_name,',
'                                    c.picture',
'                             from XXSBS_MRKT_PRODUCTS_RATINGS A,',
'                                    XXHRMS_PEOPLE B,',
'                                    XXHRMS.XXHRMS_PICTURE C',
'                             WHERE A.STAFF_ID = B.PERSON_ID',
'                             AND A.STAFF_ID = C.STAFF_ID',
'                             AND PRODUCT_ID = NVL(i.PRODUCT_ID, PRODUCT_ID)) loop',
'                       htp.p(''<div id="ratingsTabContent" class="m-content ratingsTabContent">',
'                                    <p class="m-ratings-text">''||q.rating||''</p>',
'                                <div class="m-ratings-desc">   ',
'                                    <div class="m-rating-img">',
'                                        <img  src="''||i.img_url||''" id="image" alt="Image" style="width: 20px; height: 20px; border-radius: 50%">',
'                                    </div>',
'                                    <div class="m-rating-desc-text">',
'                                        <p>''||initcap(q.full_name)||''</p>',
'                                    </div>',
'                                </div>',
'                              </div>'');',
'                   end loop;',
'                   htp.p('' </div>',
'                    <div class="myButtons">',
'                        <div class="activate-btn">',
'                            <button class="activate-button" onclick="return closeSubmitDialog();">Visit Product</button>',
'                        </div>',
'                    </div>',
'                </div>',
'              '');',
'',
'     end loop;',
'    ',
'end;'))
,p_plug_source_type=>'NATIVE_PLSQL'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(200144994713820628)
,p_plug_name=>'activate Inline Dialog'
,p_region_name=>'confirm-action'
,p_region_template_options=>'#DEFAULT#:js-dialog-size480x320:margin-left-md:margin-right-md'
,p_plug_template=>wwv_flow_imp.id(2505830901224066)
,p_plug_display_sequence=>40
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'    l_activate number := 1;',
'begin',
'      htp.p('' <html>',
'                <head>',
'                    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">',
'                </head>',
'               <body>',
'                <div>',
'                    <div class="inline-modal-header">',
'                      <div class="header-img">',
'                          <img src="#APP_IMAGES#Featured icon (1).png" />',
'                      </div>',
'                      <div class="modal-close">',
'                          <a href="" onclick="return closeInlineModal()"><img src="#APP_IMAGES#Frame 1769.png" /></a>',
'                      </div>',
'                    </div>',
'                    <div class="modal-body1">',
'                      <p class="light-p">Confirm Activation<p>',
'                      <p class="dark-p">Are you sure you want to activate the [Third-Party Service] integration?</p>',
'                    </div>',
'                    <div class="inline-submit">',
'                        <div>',
'                            <button id="myBu" class="cancel-button" onclick="return closeInlineModal()">No, Cancel</button>',
'                         </div>',
'                         <div>',
'                            <button id="myButton" class="submit-button" onclick="return completeAction(''||l_activate||'', this.id)">Visit Product</button>',
'                         </div>',
'                    </div>',
'                   ',
'             </div>',
'            </body>',
'          </html>',
'       '');',
'end;'))
,p_plug_source_type=>'NATIVE_PLSQL'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(200532510475498919)
,p_plug_name=>'deactivate Inline Dialog'
,p_region_name=>'deactivate-action'
,p_region_template_options=>'#DEFAULT#:js-dialog-size480x320:margin-left-md:margin-right-md'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(2505830901224066)
,p_plug_display_sequence=>50
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'    l_deactivate number := 0;',
'begin',
'      htp.p('' <html>',
'                <head>',
'                    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">',
'                </head>',
'               <body>',
'                <div>',
'                    <div class="inline-modal-header">',
'                      <div class="header-img">',
'                          <img src="#APP_IMAGES#Featured icon (1).png" />',
'                      </div>',
'                      <div class="modal-close">',
'                          <a href="" onclick="return closeInlineModal()"><img src="#APP_IMAGES#Frame 1769.png" /></a>',
'                      </div>',
'                    </div>',
'                    <div class="modal-body1">',
'                      <p class="light-p">Confirm Activation<p>',
'                      <p class="dark-p">Are you sure you want to de-activate the [Third-Party Service] integration?</p>',
'                    </div>',
'                    <div class="inline-submit">',
'                        <div>',
'                            <button id="myBu" class="cancel-button" onclick="return closeInlineModal()">No, Cancel</button>',
'                         </div>',
'                         <div>',
'                            <button id="myButton" class="submit-button" onclick="return completeAction(''||l_deactivate||'', this.id)">Visit Product</button>',
'                         </div>',
'                    </div>',
'                   ',
'             </div>',
'            </body>',
'          </html>',
'       '');',
'end;'))
,p_plug_source_type=>'NATIVE_PLSQL'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(99368508750672425)
,p_name=>'P67_PICTURE'
,p_item_sequence=>50
,p_item_plug_id=>wwv_flow_imp.id(199955647615657763)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(101166978559826695)
,p_name=>'P67_PRODUCT_ID'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(199955647615657763)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(101167257315826736)
,p_name=>'P67_CONFIRMED'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_imp.id(199955647615657763)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'N')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(101167644857826736)
,p_name=>'P67_ACTION'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_imp.id(199955647615657763)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'N')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(101168053841826737)
,p_name=>'P67_STATUS'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_imp.id(199955647615657763)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'N')).to_clob
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(101169072520826909)
,p_name=>'New'
,p_event_sequence=>10
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'ready'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(101169423262826916)
,p_event_id=>wwv_flow_imp.id(101169072520826909)
,p_event_result=>'TRUE'
,p_action_sequence=>20
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'apex.util.getTopApex().jQuery(".modal-dialog--pullout .ui-dialog-title").prepend(''<img src="#APP_IMAGES#Featured icon.png" style="height:48px;"/>'');'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(99368744823672427)
,p_process_sequence=>10
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GET_IMAGE'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'    v_picture varchar2(100);',
'begin',
'     DISPLAY_IMAGE(:STAFF_ID);',
'end;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_internal_uid=>99368744823672427
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(101664908095609901)
,p_process_sequence=>20
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GET_REDIRECT_URL'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'    v_ename varchar2(200);',
'begin',
'   SELECT redirect_url_ss',
'   INTO v_ename',
'   FROM XXSBS_MRKT_PRODUCTS_LISTS',
'   WHERE PRODUCT_ID = APEX_APPLICATION.g_x01',
'   AND COMPANY_CODE = :AP_cOMPANY_CODE;',
'   ',
'   if v_ename is not null then',
'       HTP.P(v_ename);',
'   else',
'       HTP.P(1);',
'   end if;',
'',
'exception when no_Data_found then ',
'HTP.P(1);',
'end;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_internal_uid=>101664908095609901
);
wwv_flow_imp.component_end;
end;
/
