prompt --application/pages/page_00030
begin
--   Manifest
--     PAGE: 00030
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>3780766536418114
,p_default_application_id=>2000007
,p_default_id_offset=>0
,p_default_owner=>'XXSBS'
);
wwv_flow_imp_page.create_page(
 p_id=>30
,p_name=>'Activate/Deativate Product'
,p_alias=>'AB33'
,p_page_mode=>'MODAL'
,p_autocomplete_on_off=>'OFF'
,p_javascript_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'var modal = document.getElementById(''main-modal'');',
'',
'function afterLoad(){',
'    apex.message.showPageSuccess(''success'');',
'}',
'',
'function testRedirect(){',
'       var x = ''Y'';',
'        var url = "f?p=#APP_ID#:"+''26''+":#SESSION#::NO:RP,26:P26_CONFIRMED:#PARA1#";',
'        url = url.replace("#APP_ID#",&APP_ID.);',
'',
'        url = url.replace("#SESSION#", &SESSION.);',
'',
'        url = url.replace("#PARA1#", x);',
'',
'        apex.server.process("PREPARE_URL", {',
'',
'                    x01: url',
'',
'        }, {',
'',
'        success: function(pData) {',
'',
'        if (pData.success === true) {',
'             //   apex.navigation.redirect(pData.url);',
'          //  console.log(url);',
'            apex.navigation.dialog.close( true);',
'',
'        } else {',
'',
'                console.log("FALSE");',
'',
'        }',
'',
'        },',
'',
'        error: function(request, status, error) {',
'',
unistr('               console.log("status\2014" + status + " error\2014-" + error);'),
'',
'        }',
'',
'    });',
'    ',
'    ',
'            return false;',
'}',
'',
'const redirectFunc = (action, status) => {',
'        $s(''P30_ACTION'', action);',
'        $s(''P30_STATUS'', status);',
'        var x = ''Y'';',
'        var url = "f?p=#APP_ID#:"+''26''+":#SESSION#::NO:RP,26:P26_CONFIRMED:#PARA1#";',
'        url = url.replace("#APP_ID#",&APP_ID.);',
'',
'        url = url.replace("#SESSION#", &SESSION.);',
'',
'        url = url.replace("#PARA1#", x);',
'',
'        apex.server.process("PREPARE_URL", {',
'',
'                    x01: url',
'',
'        }, {',
'',
'        success: function(pData) {',
'',
'        if (pData.success === true) {',
'                // null;',
'             //  apex.navigation.redirect(pData.url);',
'              apex.navigation.dialog.close( true, ["P30_ACTION","P30_STATUS", "P30_PRODUCT_ID"] );',
'',
'        } else {',
'',
'                console.log("FALSE");',
'',
'        }',
'',
'        },',
'',
'        error: function(request, status, error) {',
'',
unistr('               console.log("status\2014" + status + " error\2014-" + error);'),
'',
'        }',
'',
'    });',
'    ',
'    ',
'            return false;',
'        ',
'};',
'',
'function open_dialog(){',
' $(''#confirm-action'').dialog(''open''); //calling region id here to open',
'    return false;',
'}',
'',
'function openDeactivateDialog(){',
' $(''#deactivate-action'').dialog(''open''); //calling region id here to open',
'    return false;',
'}',
'',
'function closeMainModal(){',
'    $(''#modalwindow'').modal(''hide'');',
'    //  javascript:apex.navigation.dialog.close(true);',
'    return false;',
'}',
'',
'function closeModal(){',
'    apex.navigation.dialog.close(true);',
'    return false;',
'}',
'function closeInlineModal(){',
'     $(''#confirm-action'').dialog(''close''); ',
'     $(''#deactivate-action'').dialog(''close''); ',
'    return false;',
'}',
'',
'',
'function completeAction(action, id){',
'    let product_id = $v(''P30_PRODUCT_ID'');',
'    if(action == 1){ // 1 means activate',
'      apex.server.process("COMPLETE_ACTION", {',
'        x01:  ''A'',',
'        x02:  product_id,',
'      }, {',
'',
'        dataType: ''text'',',
'        success: function(pData) {',
'            if(pData == 1){ // 1 means successful',
'                redirectFunc(''activate'', ''S''); // activate and successful',
'            }else{ ',
'                redirectFunc(''activate'', ''F''); //activate and failed',
'            }',
'        }',
'      });',
'    }else{',
'        apex.server.process("COMPLETE_ACTION", {',
'            x01:  ''I'',',
'            x02:  product_id,',
'          }, {',
'',
'            dataType: ''text'',',
'            success: function(pData) {',
'                if(pData == 1){ // 1 means successful',
'                   redirectFunc(''deactivate'', ''S''); // activate and successful',
'                }else{ ',
'                   redirectFunc(''deactivate'', ''F''); //activate and failed',
'                }',
'            }',
'          });',
'    }',
'    return false;',
'}',
''))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'.now-p .text {',
'  font-size: 13px;',
'  padding-left: 40px;',
'}',
'',
'.now-p{',
'   font:Helvetica;',
'   color: #423B3B;',
'}',
'',
'.now-bold-text{',
'    font-family: Helvetica;',
'    font-size: 16px;',
'    font-weight: 700;',
'    line-height: 30px;',
'    text-align: left;',
'    color:#423B3B;',
'}',
'',
'.modal-header{',
'  display: flex;',
'  flex-wrap: wrap;',
'  align-items:center;',
'  justify-content:space-between;',
'    background-color: #FFFFFF;',
'    padding: 15px;',
'    text-align: center;',
'    position: fixed;',
'    top: 0;',
'    left: 0;',
'    width: 100%;',
'   /* height: 75px;*/',
'    z-index: 10;',
'    /*top: 0;',
'    position:fixed;',
'    width: 100%;*/',
'}',
'',
'.modal-header img{',
'   margin: 5px 0px;',
'   padding: 0px 9px;',
'   width:86%;',
'   height:auto;',
'   object-fit:cover;',
'   object-position:50% 50%;',
'}',
'',
'.modal-body-main{',
'    padding-top: 60px;  ',
'    padding-bottom: 60px; ',
'    margin: 0 auto;',
'    height: calc(100vh -100px);  ',
'    overflow-y: auto;  ',
'    /*overflow: hidden;*/  ',
'    ',
'}',
'',
'.modal-body1{',
'    margin: 12px 0px;',
'}',
'',
'.modal-product-title{',
'    display: flex;',
'  flex-wrap: wrap;',
'  align-items:center;',
'  justify-content:space-between;',
'}',
'',
'',
'.modal-product-title span{',
'      background-color:#F2F4F7;',
'    width: Hug (62px)px;',
'    height: Hug (22px)px;',
'    padding: 2px 8px;',
'    gap: 0px;',
'    border-radius: 16px;',
'    opacity: 0px;',
'    font-size: 12px;',
'    font-weight: 500;',
'    text-align: center;',
'    color:#344054;',
'    font-weight: 500;',
'    line-height: 18px;',
'}',
'',
'.company-description{',
'    margin-top: 12px;',
'}',
'',
'.company-description p{',
'    font-size: 14px;',
'}',
'.product-description{',
'    margin: 12px 0px;',
'    border-top: 1px solid #EAEAEA;',
'}',
'',
'.product-description2{',
'    margin: 12px 0px;',
'    border-top: 1px solid #EAEAEA;',
'}',
'',
'.activate-btn{',
'    margin-top: 12px;',
'    border-top: 1px solid #EAEAEA;',
'}',
'',
'.activate-button{',
'    display: block;',
'    width: 100%;',
'    padding: 15px 0px;',
'    margin-top: 12px;',
'    border-radius: 4px;',
'    cursor: pointer;',
'    background: #348BEF;',
'    border:none;',
'    font-family: Helvetica;',
'    font-size: 14px;',
'    font-weight: 700;',
'    line-height: 16.1px;',
'    letter-spacing: -0.01em;',
'    color: #FFFFFF;',
'}',
'',
'.deactivate-button{',
'    display: block;',
'    width: 100%;',
'    padding: 15px 0px;',
'    margin-top: 12px;',
'    border-radius: 4px;',
'    cursor: pointer;',
'    background: #348BEF;',
'    border:none;',
'    font-family: Helvetica;',
'    font-size: 14px;',
'    font-weight: 700;',
'    line-height: 16.1px;',
'    letter-spacing: -0.01em;',
'    color: #FFFFFF;',
'}',
'',
'.description-header{',
'    font-family: Helvetica;',
'    font-size: 16px;',
'    font-weight: 700;',
'    line-height: 24px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none; ',
'    width: Fill (531px)px;',
'    height: Fixed (48px)px;',
'    padding: 8px 0px 0px 0px;',
'    gap: 8px;',
'    border-radius: 4px 0px 0px 0px;',
'    opacity: 0px;',
'    color: #423B3B;',
'}',
'',
'',
'.myButtons{',
'    background:#FFFFFF;',
'    color: white;',
'    padding: 0px 15px;',
'    padding-bottom: 15px;',
'    text-align: center;',
'    position: fixed;',
'    bottom: 0;',
'    left: 0;',
'    width: 100%;',
'    z-index: 10;',
'}',
'/*Inline Dialog*/',
'.ui-dialog-titlebar{',
'    display:none;',
'}',
'',
'.ui-dialog{',
'     width: 80%!important;',
'    height:43%!important;',
'    top: 25%!important;',
'    border-radius: 12px!important;',
'}',
'',
'.t-DialogRegion-body{',
'    padding: 10px 0px;',
'}',
'',
'',
'.inline-modal-header{',
'     display: flex;',
'  flex-wrap: wrap;',
'  align-items:center;',
'  justify-content:space-between;',
'}',
'',
'.inline-modal-header img{',
'   width:65%;',
'   height:auto;',
'   object-fit:cover;',
'   object-position:50% 50%;',
'}',
'',
'.light-p{',
'    styleName: Text sm/Regular;',
'    font-family: Helvetica;',
'    font-size: 14px;',
'    font-weight: 400;',
'    line-height: 20px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'    color: #667085;',
'}',
'',
'.dark-p{',
'    font-family: Helvetica;',
'    font-size: 14px;',
'    font-weight: 700;',
'    line-height: 28px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'    color: #101828;',
'}',
'',
'/*Inline dialog buttons*/',
'.inline-submit{',
'    display: flex;',
'  flex-wrap: wrap;',
'  align-items:center;',
'  justify-content:space-between;',
'  margin-top: 30px;',
'}',
'',
'.cancel-button{',
'    width: Fixed (210px)px;',
'    height: Fixed (48px)px;',
'    padding: 8px 40px;',
'    gap: 0px;',
'    border-radius: 4px;',
'    border: 1px solid #7D7D7D;',
'    font-family: Helvetica;',
'    font-size: 14px;',
'    font-weight: 700;',
'    line-height: 16.1px;',
'    letter-spacing: -0.01em;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'    color: #7D7D7D;',
'}',
'',
'.submit-button{',
'    width: 100%;',
'    height: Fixed (48px)px;',
'    padding: 8px 40px;',
'    gap: 0px;',
'    border-radius: 4px;',
'    border: none;',
'    background: #348BEF;',
'    color:#FFFFFF;',
'    font-family: Helvetica;',
'    font-size: 14px;',
'    font-weight: 700;',
'    line-height: 16.1px;',
'    letter-spacing: -0.01em;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'}',
''))
,p_page_template_options=>'#DEFAULT#'
,p_dialog_height=>'535'
,p_dialog_width=>'500'
,p_dialog_max_width=>'500'
,p_dialog_css_classes=>'modal-dialog--pullout'
,p_page_component_map=>'10'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(98789372045831246)
,p_plug_name=>'&nbsp'
,p_region_name=>'main-modal'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(5431141257166683)
,p_plug_display_sequence=>30
,p_include_in_reg_disp_sel_yn=>'Y'
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'    l_content clob;',
'    q_content clob;',
'    v_data clob;',
'begin',
'',
'    for i in (select ',
'              product_id,',
'              product_name,',
'              product_description,',
'              company_desc,',
'              new_price,',
'              old_price,',
'              decode(product_status, ''A'', ''Active'', ''I'', ''Inactive'') status',
'              from XXSBS_MRKT_PRODUCTS_LISTS',
'              where product_id = :P30_PRODUCT_ID',
'              and company_code = :AP_cOMPANY_cODE)',
'    loop',
'    ',
'        htp.p('' <div class = "container">',
'                    <div class="modal-header">',
'                      <div class="header-img">',
'                          <img src="#APP_IMAGES#Featured icon.png" />',
'                      </div>',
'                      <div class="modal-close">',
'                          <a href="" onclick="return testRedirect()"><img src="#APP_IMAGES#Frame 1769.png" /></a>',
'                      </div>',
'                    </div>',
'                    <div class= "modal-body-main content" id="very-important-read">',
'                        <div class="modal-body1">',
'                          <p class="now-p">',
unistr('                              <span style="font-size:16px; line-height:24px;"><b>\20A6''||i.new_price||''</b></span>'),
unistr('                              <span style="text-decoration: line-through; font-size: 16px; padding-left: 10px;">\20A6''||i.old_price||''</span></p>'),
'                          <div class="modal-product-title">',
'                              <div>',
'                                  <p class="now-bold-text">''||i.product_name||''</p>',
'                              </div>',
'                              <div>'');',
'                                if i.status = ''Active'' then',
'                                    htp.p(''<span style="background:#ECFDF3;">''||i.status||''</span>'');',
'                                else',
'                                    htp.p(''<span>''||i.status||''</span>'');',
'                                end if;',
'                              htp.p(''</div>',
'                              <div class="company-description">',
'                                  <p style="font-size: 14px;">''||i.company_desc||''</p>',
'                              </div>',
'                          </div>',
'                        </div>',
'                        <div class="product-description">',
'                              <p class="description-header">Description</p>',
'                              <p style="font-size: 14px;">''||i.product_Description||''</p>',
'                        <div>',
'                         <div class="product-description2">',
'                              <p class="description-header">Key Features</p>',
'                                  <ul>''',
'                 );',
'',
'                    for q in (select *',
'                              from XXSBS_MRKT_PRODUCTS_LISTS_DET',
'                              where product_id = i.product_id',
'                              and company_code = :AP_cOMPANY_cODE)',
'                    loop',
'                     htp.p(''',
'                                  <li style="font-size:14px;">''||q.features||''</li>        ',
'                     '');',
'                     end loop;',
'                     htp.p(''',
'                        </ul>',
'                        </div>',
'                    </div>   ',
'                    <div class="myButtons"> '');',
'                       if i.status= ''Inactive'' then',
'                            htp.p('' <div class="activate-btn">',
'                                  <button class="activate-button" onclick="return open_dialog();">Activate Service</button>',
'                            </div>'');',
'                        else',
'                            htp.p(''<div class="deactivate-btn">',
'                                  <button class="deactivate-button" onclick="return openDeactivateDialog();">Deactivate Service</button>',
'                            </div>'');',
'                        end if;',
'                  htp.p(''</div>',
'               '');',
'',
'     end loop;',
'    ',
'end;'))
,p_plug_source_type=>'NATIVE_PLSQL'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(98978719143994111)
,p_plug_name=>'activate Inline Dialog'
,p_region_name=>'confirm-action'
,p_region_template_options=>'#DEFAULT#:js-dialog-size480x320:margin-left-md:margin-right-md'
,p_plug_template=>wwv_flow_imp.id(5449458935166697)
,p_plug_display_sequence=>40
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'    l_activate number := 1;',
'begin',
'      htp.p('' <html>',
'                <head>',
'                    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">',
'                </head>',
'               <body>',
'                <div>',
'                    <div class="inline-modal-header">',
'                      <div class="header-img">',
'                          <img src="#APP_IMAGES#Featured icon (1).png" />',
'                      </div>',
'                      <div class="modal-close">',
'                          <a href="" onclick="return closeInlineModal()"><img src="#APP_IMAGES#Frame 1769.png" /></a>',
'                      </div>',
'                    </div>',
'                    <div class="modal-body1">',
'                      <p class="light-p">Confirm Activation<p>',
'                      <p class="dark-p">Are you sure you want to activate the [Third-Party Service] integration?</p>',
'                    </div>',
'                    <div class="inline-submit">',
'                        <div>',
'                            <button id="myBu" class="cancel-button" onclick="return closeInlineModal()">No, Cancel</button>',
'                         </div>',
'                         <div>',
'                            <button id="myButton" class="submit-button" onclick="return completeAction(''||l_activate||'', this.id)">Yes, Activate</button>',
'                         </div>',
'                    </div>',
'                   ',
'             </div>',
'            </body>',
'          </html>',
'       '');',
'end;'))
,p_plug_source_type=>'NATIVE_PLSQL'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(99366234905672402)
,p_plug_name=>'deactivate Inline Dialog'
,p_region_name=>'deactivate-action'
,p_region_template_options=>'#DEFAULT#:js-dialog-size480x320:margin-left-md:margin-right-md'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(5449458935166697)
,p_plug_display_sequence=>50
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'    l_deactivate number := 0;',
'begin',
'      htp.p('' <html>',
'                <head>',
'                    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">',
'                </head>',
'               <body>',
'                <div>',
'                    <div class="inline-modal-header">',
'                      <div class="header-img">',
'                          <img src="#APP_IMAGES#Featured icon (1).png" />',
'                      </div>',
'                      <div class="modal-close">',
'                          <a href="" onclick="return closeInlineModal()"><img src="#APP_IMAGES#Frame 1769.png" /></a>',
'                      </div>',
'                    </div>',
'                    <div class="modal-body1">',
'                      <p class="light-p">Confirm Activation<p>',
'                      <p class="dark-p">Are you sure you want to de-activate the [Third-Party Service] integration?</p>',
'                    </div>',
'                    <div class="inline-submit">',
'                        <div>',
'                            <button id="myBu" class="cancel-button" onclick="return closeInlineModal()">No, Cancel</button>',
'                         </div>',
'                         <div>',
'                            <button id="myButton" class="submit-button" onclick="return completeAction(''||l_deactivate||'', this.id)">Yes, Deactivate</button>',
'                         </div>',
'                    </div>',
'                   ',
'             </div>',
'            </body>',
'          </html>',
'       '');',
'end;'))
,p_plug_source_type=>'NATIVE_PLSQL'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(98789425865831247)
,p_name=>'P30_PRODUCT_ID'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(98789372045831246)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(98981379639994137)
,p_name=>'P30_CONFIRMED'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_imp.id(98789372045831246)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'N')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(99366749337672407)
,p_name=>'P30_ACTION'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_imp.id(98789372045831246)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'N')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(99366884735672408)
,p_name=>'P30_STATUS'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_imp.id(98789372045831246)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'N')).to_clob
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(98978108102994105)
,p_name=>'New'
,p_event_sequence=>10
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'ready'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(98978267974994106)
,p_event_id=>wwv_flow_imp.id(98978108102994105)
,p_event_result=>'TRUE'
,p_action_sequence=>20
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'apex.util.getTopApex().jQuery(".modal-dialog--pullout .ui-dialog-title").prepend(''<img src="#APP_IMAGES#Featured icon.png" style="height:48px;"/>'');'
);
wwv_flow_imp.component_end;
end;
/
