prompt --application/shared_components/logic/application_processes/user_details
begin
--   Manifest
--     APPLICATION PROCESS: user_details
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>3780766536418114
,p_default_application_id=>2000007
,p_default_id_offset=>0
,p_default_owner=>'XXSBS'
);
wwv_flow_imp_shared.create_flow_process(
 p_id=>wwv_flow_imp.id(18744340608433305)
,p_process_sequence=>1
,p_process_point=>'AFTER_LOGIN'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'user_details'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'  --',
' ',
'  ',
'  CURSOR c_dtl IS',
'  SELECT initcap(x.full_name), x.person_type, x.staff_category, x.department,y.staff_id, x.dept_Code, x.organization_id,x.company_name,nvl(y.SUB_ORG,''0'')SUB_ORG, nvl(y.DEPARTMENT,''0'')DEPARTMENT, nvl(y.unit,''0'')unit ',
'   FROM xxhrms.xxhrms_master_all x, xxadm.xxadm_password y',
'  WHERE y.staff_id = x.employee_number(+)',
'    AND UPPER(y.logname) = UPPER(:APP_USER);',
'  --',
'  cursor c_pwd is ',
'  select  y.logname,  y.password_change, y.LEVELS',
'    from xxadm.xxadm_password y',
'   where UPPER(y.logname) = UPPER(:APP_USER);',
'  --  ',
'CURSOR c_lbl(p_id VARCHAR2) IS',
'SELECT  legacy_acct_label,',
'        STAFF_ID_LABEL,',
'        LEGACY_LABEL,',
'        JOBTITLE_LABEL,',
'        DEPARTMENT_LABEL,',
'        GRADE_LABEL,',
'        EMAIL_ADDRESS_LABEL,',
'        POSITION_LABEL,',
'        FULLNAME_LABEL,',
'        EMPLOYEESTATUS_LABEL,',
'        UNIT_LABEL,  ',
'        ANNUAL_GROSS_LABEL,  ',
'        FIRST_NAME_LABEL,',
'        LAST_NAME_LABEL, ',
'        MONTHLY_GROSS_LABEL,',
'        PERSON_TYPE_LABEL, ',
'        START_DATE, ',
'        ASSIGNMENT_START_DATE_LABEL, ',
'        PERSON_START_DATE_LABEL, ',
'        ORIGINAL_DATE_OF_HIRE_LABEL, ',
'        DATE_OF_BIRTH_LABEL,  ',
'        MAR_STATUS_LABEL, ',
'        SEX_LABEL, ',
'        SUB_ORGANIZATION_LABEL,',
'        STATE_OF_ORIGIN_LABEL, ',
'        LOCATION_LABEL, ',
'        SUPERVISOR_LABEL,',
'        TITLE_LABEL,',
'        ORGANIZATION_LABEL,',
'        EMPLOYEEINFORMATION_LABEL,',
'        EMPLOYEETYPE_LABEL,',
'        COMPANYNAME_LABEL',
'FROM xxhrms.xxhrms_companyinfo',
' WHERE company_code = p_id;',
'',
'',
'--',
'begin',
'  --',
'  :AP_GLOBAL_DATE := TRUNC(SYSDATE);',
'  --',
'  OPEN c_dtl;',
'  FETCH c_dtl INTO :AP_FULL_NAME, :AP_TYPE, :AP_CATEGORY, :AP_DEPARTMENT, :AP_STAFF_ID, :AP_DEP_CODE, :AP_COMPANY_CODE,:AP_COMPANY_NAME,:AP_USUB_ORG,:AP_UDEPT,:AP_UUNIT;',
'  CLOSE c_dtl; ',
'  --',
'  ',
'  ',
'  OPEN c_pwd;',
'  FETCH c_pwd INTO :AP_USERNAME, :AP_CHANGE_PASSWORD, :AP_ACCESS_LEVEL;',
'  CLOSE c_pwd; ',
'   ',
'  ',
'  --',
'OPEN c_lbl(:AP_COMPANY_CODE);',
'FETCH c_lbl INTO :AP_EMP_LBL,',
'  :AP_STAFF_ID_LABEL, ',
'  :AP_LEGACY_LABEL,',
'  :AP_JOBTITLE_LABEL,',
'  :AP_DEPARTMENT_LABEL,',
'  :AP_GRADE,',
'  :AP_EMAIL,',
'  :AP_POSITION_LABEL,',
'  :AP_FULLNAME_LABEL,',
'  :AP_STATUS,',
'  :AP_UNIT_LABEL,',
'  :AP_ANNUAL_GS_LABEL,',
'  :AP_FIRSTNAME,',
'  :AP_LASTNAME,',
'  :AP_MONTHLY_GS_LABEL,  ',
'  :AP_PERSONTYPE,',
'  :AP_STARTDATE,',
'  :AP_ASSDATE,',
'  :AP_PERSONSTARTDATE,',
'  :AP_ODOHIRE_LABEL,',
'  :AP_DOB_LABEL,',
'  :AP_MARSTATUS,',
'  :AP_SEX,',
'  :AP_SUBORG_LABEL,',
'  :AP_STATE,',
'  :AP_LOCATION_LABEL,',
'  :AP_SUPERVISOR,',
'  :AP_TITLE_LABEL,',
'  :AP_ORGANIZATION_LABEL,',
'  :AP_EmployeeInformation,',
'  :AP_EmployeeType,',
'  :AP_ComapanyName;',
'  ',
'CLOSE c_lbl; ',
'  :AP_EMP_LBL := NVL(:AP_EMP_LBL, ''Legacy Account ID'');',
'  :AP_STAFF_ID_LABEL := NVL(:AP_STAFF_ID_LABEL, ''Staff ID'');',
'  :AP_LEGACY_LABEL := NVL(:AP_LEGACY_LABEL, ''Legacy ID'');',
'  :AP_JOBTITLE_LABEL := NVL(:AP_JOBTITLE_LABEL,''Job Title'');',
'  :AP_DEPARTMENT_LABEL := NVL(:AP_DEPARTMENT_LABEL,''Department'');',
'  :AP_GRADE := NVL(:AP_GRADE,''Grade'');',
'  :AP_FULLNAME_LABEL := NVL(:AP_FULLNAME_LABEL,''Employee Name'');',
'  :AP_EMAIL := NVL(:AP_EMAIL, ''Email Address'');',
'  :AP_POSITION_LABEL  := NVL(:AP_POSITION_LABEL,''Position'');',
'  :AP_STATUS  := NVL(:AP_STATUS, ''Status'');',
'  :AP_UNIT_LABEL := NVL(:AP_UNIT_LABEL, ''Unit'');',
'  :AP_ANNUAL_GS_LABEL := NVL(:AP_ANNUAL_GS_LABEL, ''Annual Gross Salary''); ',
'  :AP_FIRSTNAME := NVL(:AP_FIRSTNAME, ''First Name'');',
'  :AP_LASTNAME  := NVL(:AP_LASTNAME, ''Last Name'');',
'  :AP_MONTHLY_GS_LABEL := NVL(:AP_MONTHLY_GS_LABEL, ''Monthly Gross Salary''); ',
'  :AP_PERSONTYPE := NVL(:AP_PERSONTYPE,''Person Type'');',
'  :AP_STARTDATE := NVL(:AP_STARTDATE, ''Start Date'');',
'  :AP_ASSDATE := NVL(:AP_ASSDATE, ''Assignment State Date'');',
'  :AP_PERSONSTARTDATE := NVL(:AP_PERSONSTARTDATE, ''Person Start Date'');',
'  :AP_ODOHIRE_LABEL := NVL(:AP_ODOHIRE_LABEL, ''Origin Date Of Hire'');',
'  :AP_DOB_LABEL :=NVL(:AP_DOB_LABEL, ''Date Of Birth'');',
'  :AP_MARSTATUS := NVL(:AP_MARSTATUS, ''Marital Status'');',
'  :AP_SEX := NVL(:AP_SEX, ''Sex'');',
'  :AP_SUBORG_LABEL := NVL(:AP_SUBORG_LABEL, ''Sub Organization'');',
'  :AP_STATE := NVL(:AP_STATE, ''State Of Origin'');',
'  :AP_LOCATION_LABEL := NVL(:AP_LOCATION_LABEL,''Location'');',
'  :AP_SUPERVISOR := NVL(:AP_SUPERVISOR,''Supervisor'');',
'  :AP_TITLE_LABEL := NVL(:AP_TITLE_LABEL,''Title'');',
'  :AP_ORGANIZATION_LABEL := NVL(:AP_ORGANIZATION_LABEL,''Organization'');',
'  :AP_EmployeeInformation := NVL(:AP_EMPLOYEEINFORMATION,''Employee Information'');',
'  :AP_EmployeeType := NVL(:AP_EMPLOYEETYPE,''Employee Type'');',
'  :AP_ComapanyName := NVL(:AP_COMPANYNAME,''Company Name'');',
'  ',
'  --                ',
'  ',
'  --',
'end;'))
,p_process_clob_language=>'PLSQL'
,p_version_scn=>1
);
wwv_flow_imp.component_end;
end;
/
